Update Typography T-shirt sizing syntax
adobe/spectrum-css pull request #1031
Opened 2020-10-01 18:28 UTC by GarthDB

## Description
Change the typography t-shirt size classes from `.spectrum-Heading--XXXL` to `.spectrum-Heading--sizeXXXL`

## To-do list

- [x] If my change impacts other components, I have tested to make sure they don't break.
- [ ] If my change impacts documentation, I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).

- [ ] This pull request is ready to merge.

2020-10-01 18:29 UTC, GarthDB commented
I need to update migration guides; I just want to check VRT.

2020-10-15 18:12 UTC, lazd requested changes
Couple of little errors, once those are fixed I'll check it out locally and see if it's good to go.

2020-10-15 18:12 UTC, lazd commented on components/rating/metadata/rating.yml
> +          <svg class="spectrum-Icon spectrum-UIIcon-sizeStar spectrum-Rating-starActive" focusable="false" aria-hidden="true">
Regex got over excited here

2020-10-15 18:12 UTC, lazd commented on tools/component-builder/css/processors.js
> +          // ".spectrum-Detail--sizXL em {}"
Missing that elusive `e`

2020-10-15 18:45 UTC, lazd requested changes
I'm thinking if we get the migration guide updated to point at the new-new classes, and if VRT does not fail anywhere, this is good.

2020-10-15 18:45 UTC, lazd commented on components/typography/metadata/typography.yml
>    - name: Migrating from deprecated Typography
Can we also update this section to show the new-new typography classes, not the old-new? i.e.

```
| `~.spectrum-Heading1--display~`  | `.spectrum-Heading.spectrum-Heading--sizeXXXL`                        ```

2020-10-15 18:55 UTC, lazd approved these changes

2020-10-15 19:03 UTC, merged