fix: updated to @adobe/spectrum-tokens@7.0.0-beta.20
adobe/spectrum-css pull request #1210
Opened 2021-06-11 21:12 UTC by lazd

## Description

beta.20 + fixes to renamed aliases

## How and where has this been tested?
 - **How this was tested:** locally, with eyes

2021-06-11 21:51 UTC, GarthDB requested changes
This is failing the `yarn audit-cli --moderate`. If you fix them, we can check the VRT easier.

2021-06-11 23:14 UTC, lazd commented
@GarthDB can you go ahead and fix the issues and push to this branch? Thanks!

2021-06-15 23:04 UTC, lazd commented
@GarthDB I pushed a commit that disables checking `audit` before running VRT -- there's already a separate task that runs audit, so this should make it so VRT doesn't depend on audit passing.

Please let me know if this is good to go!

2021-06-16 18:20 UTC, GarthDB requested changes

2021-06-16 18:20 UTC, GarthDB commented on components/vars/css/components/spectrum-actionbutton.css
> +  --spectrum-actionbutton-s-quiet-emphasized-texticon-#padding-text: var(--spectrum-global-dimension-size-115);
We're getting `#` symbols in our variables names.

2021-06-16 18:20 UTC, GarthDB commented on components/vars/css/components/spectrum-actionbutton.css
> +  --spectrum-actionbutton-s-quiet-emphasized-texticon-#padding-text: var(--spectrum-global-dimension-size-115);
Looks like it's a fairly widespread problem.

* actionbutton
* button
* checkbox
* clearbutton
* cyclebutton
* link
* listitem
* panel
* radio
* rating
* scrollbar
* search
* switch
* tag
* textarea
* textfield

2021-06-16 18:29 UTC, GarthDB commented on components/vars/css/components/spectrum-actionbutton.css
> +  --spectrum-actionbutton-s-quiet-emphasized-texticon-#padding-text: var(--spectrum-global-dimension-size-115);
Looks like it's coming from `@adobe/spectrum-tokens`. I double checked and this is on version `7.0.0-beta.21`

2021-06-17 22:23 UTC, merged