feat(thumbnail)!: use new vars & create new class names
adobe/spectrum-css pull request #1313
Opened 2021-11-08 18:41 UTC by pfulton

## Description

## How and where has this been tested?
 - **How this was tested:** 
 - **Browser(s) and OS(s) this was tested with:** 

## Screenshots

## To-do list

- [ ] If my change impacts other components, I have tested to make sure they don't break.
- [ ] If my change impacts documentation, I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).

- [x] This pull request is ready to merge.

2021-11-09 18:57 UTC, pfulton commented
The checkerboard background is slightly darker in Express, due to the differences in the color vars used for the themes. Is this a problem? Is the checkerboard actually used in production-facing things, or is it simply for demonstration purposes?

I think the solution would be to hard-code a consistent color between the two themes, but I need some guidance/answers on those questions above.

<img width="326" alt="spectrum-thumbnail" src="https://user-images.githubusercontent.com/360251/140986889-aba68c62-85e0-428e-b215-001c99c031a5.png">
<img width="320" alt="express-thumbnail" src="https://user-images.githubusercontent.com/360251/140986891-b60555c2-4b52-4ca8-886d-e2bfddcf0405.png">

2021-11-09 19:05 UTC, GarthDB commented
I don't think it's necessary to fix the checkerboard to be consistent for this pr, but you can double check with design in qotd if you'd like.

2021-11-10 03:19 UTC, lazd requested changes
Drive checkerboard colors with the tokens and I think you've got it!

2021-11-10 03:19 UTC, lazd commented on components/thumbnail/skin.css
> +    linear-gradient(45deg, var(--spectrum-global-color-static-gray-200) 25.5%, transparent 25.5%);
You can totally drive these with:

```
--spectrum-thumbnail-m-layer-darksquare-background-color
--spectrum-thumbnail-m-layer-lightsquare-background-color
```

2021-11-10 03:23 UTC, lazd commented on components/thumbnail/metadata/thumbnail.yml
>      description: Rectangular images will fill the entire space.
Add a migration guide like

```
sections:
  - name: Migration Guide
    description: |
        ### T-shirt sizing
        Thumbnail now supports t-shirt sizing with the standard naming convention and requires that you specify the size by adding a `.spectrum-Thumbnail--size*` class.

      | Deprecated Classname | New Classname           |
      | -------------------- | ----------------------- |
      | `~.spectrum-Thumbnail-XXL~` | `.spectrum-Thumbnail--sizeXXL`|
      | `~.spectrum-Thumbnail-XL~` | `.spectrum-Thumbnail--sizeXL`|
      | `~.spectrum-Thumbnail-L~` | `.spectrum-Thumbnail--sizeL` |
      | `~.spectrum-Thumbnail-M~` | `.spectrum-Thumbnail--sizeM` |
      | `~.spectrum-Thumbnail-S~` | `.spectrum-Thumbnail--sizeS` |
```

2021-11-10 22:53 UTC, merged