chore: Storybook implementation
adobe/spectrum-css pull request #1539
Opened 2022-10-26 14:45 UTC by castastrophe

- Add storybook with helptext example
- Add global css to storybook
- Add story-decorator customized for local CSS

## Description

## How and where has this been tested?
 - **How this was tested:** 
 - **Browser(s) and OS(s) this was tested with:** 

## Screenshots

## To-do list

- [ ] If my change impacts other components, I have tested to make sure they don't break.
- [ ] If my change impacts documentation, I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).
- [ ] I have tested these changes in Windows High Contrast mode.

- [ ] This pull request is ready to merge.

2022-12-01 21:19 UTC, castastrophe commented on tools/preview/README.md
> +# @spectrum-css/preview
Todo: need to fill this out

2022-12-12 20:43 UTC, pfulton requested changes
Wow, this is awesome @castastrophe. 🎉 

My one bit of feedback at this time is that we should get rid of the option for `lightest`, as we've deprecated it.

2022-12-13 02:50 UTC, castastrophe reviewed
Removing lightest via GitHub UI

2022-12-13 02:50 UTC, castastrophe commented on tools/preview/decorators/contextsWrapper.js
> +import '@spectrum-css/vars/dist/spectrum-lightest.css';
```suggestion
```

2022-12-13 02:50 UTC, castastrophe commented on tools/preview/decorators/contextsWrapper.js
> +      ['lightest', 'light', 'dark', 'darkest'].forEach(c => document.body.classList.remove(`spectrum--${c}`));
```suggestion
      ['light', 'dark', 'darkest'].forEach(c => document.body.classList.remove(`spectrum--${c}`));
```

2022-12-13 02:50 UTC, castastrophe commented on tools/preview/preview.js
> +      options: ['lightest', 'light', 'dark', 'darkest'],
```suggestion
      options: ['light', 'dark', 'darkest'],
```

2022-12-13 02:50 UTC, castastrophe commented on tools/preview/preview.js
> +          lightest: 'Lightest',
```suggestion
```

2022-12-13 20:33 UTC, merged