chore: component generator [CSS-283]
adobe/spectrum-css pull request #1573
Opened 2023-01-05 20:26 UTC by castastrophe

## Description

This PR introduces 2 new generators for the project (and corresponding documentation):

1. `yarn new component`
2. `yarn new story`

The component generator prompts the user for a component name (in human-readable format) and will reject the input if the name already exists in the library.  When run, it will generate a component using the new token system format and will include the storybook templated assets.  After generating the files, it will run `yarn install` to register the component in the monorepo.

The story generator asks the user to type the name of an existing component (using an autocomplete feature) and it will generate a new stories directory with *.stories.js and template.js assets. In the template.js asset, you will note that it includes an example of markup which was captured from the metadata/*.yml file. It will skip over any assets that already exist making this a non-destructive command.

## How and where has this been tested?
 - **How this was tested:** 
  - [ ] `yarn new` - expected to prompt the user to select either the component or the story generator, then proceeds into the prompts for the chosen generator.
  - [ ] `yarn new component` - expected to prompt for a component name.
    - [ ] If a name is entered for a folder that already exists in the library, a warning is thrown and the prompt asks again for a name.
    - [ ] If a unique name is entered, the assets are generated for the component as expected and then `yarn install` is run with no errors. A success message should close out the command.
  - [ ] `yarn new component foo` - expected to skip all user prompts and generate the assets.
  - [ ] `yarn new story actionbutton` - expected to skip all user prompts and generate the storybook assets only.
    - [ ] If the assets already exist, it should note this in the console and exit without changes.

 - **Browser(s) and OS(s) this was tested with:** 

## Screenshots

## To-do list

- [x] If my change impacts other components, I have tested to make sure they don't break.
- [x] If my change impacts documentation, I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).
- [x] This pull request is ready to merge.

2023-01-05 20:34 UTC, castastrophe commented
@pfulton I am on a Mac when I validated this update - do you know of anyone on the team with a Windows setup who could validate this works for them as well?

2023-01-05 21:03 UTC, pfulton commented
> @pfulton I am on a Mac when I validated this update - do you know of anyone on the team with a Windows setup who could validate this works for them as well?

We should check on this, but no one comes to mind right now! We might be able to reach out to the larger org, though!

2023-01-05 22:02 UTC, castastrophe commented
Validated on Windows by @orangegloves ✅

2023-01-06 22:02 UTC, pfulton requested changes
Woo! This is _awesome_ @castastrophe! I left a few things here, but I was able to run through creating:
* a new component
* just stories
* a new component with an existing name

And everything worked so well. Thanks for the effort on this one.

2023-01-07 03:54 UTC, castastrophe commented on components/README.md
> +  5a. In the `*.stories.js` file, define the available knobs and properties for your component, as well as any standard variations you want to surface in [Storybook](https://storybook.js.org/docs/rea
I updated this to use bullet points instead since the order of the tasks isn't necessarily important.

2023-01-07 03:54 UTC, castastrophe commented on tools/generator/plopfile.js
> +	// plop.setHelper('or', () => Array.prototype.slice.call(arguments, 0, -1).some(Boolean));
Oh yes, thanks for spotting that

2023-01-07 03:54 UTC, castastrophe commented on tools/generator/templates/index.css.hbs
> +Copyright 2022 Adobe. All rights reserved.
haha copy and paste strikes again!

2023-01-09 15:26 UTC, pfulton approved these changes

2023-01-09 15:27 UTC, merged