chore: update dates; minor ci fixes
adobe/spectrum-css pull request #1805
Opened 2023-04-25 12:26 UTC by castastrophe

## Description

## How and where has this been tested?
 - **How this was tested:** 
 - **Browser(s) and OS(s) this was tested with:** 

## Screenshots

## To-do list

- [ ] If my change impacts other components, I have tested to make sure they don't break.
- [ ] If my change impacts documentation, I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).
- [ ] I have tested these changes in Windows High Contrast mode.
- [ ] I have updated any relevant storybook stories and templates. 

- [ ] This pull request is ready to merge.

2023-04-25 12:34 UTC, castastrophe commented on README.md
> +- First, be sure that you're working on a branch other than `main`.
Some of this is because I ran it through prettier manually to catch any stray typos or minor issues

2023-04-26 10:37 UTC, Rajdeepc requested changes

2023-04-26 10:37 UTC, Rajdeepc commented on README.md
> +@import "node_modules/@spectrum-css/vars/dist/spectrum-global.css";
Is there any specific reason we have updated the single quote to double quotes?
Can we go by a unified lint rule approach?

2023-04-26 10:37 UTC, Rajdeepc commented on README.md
> +    require("postcss-import"),
These changes are not required. Can we revert to its original single quote?

2023-04-26 10:37 UTC, Rajdeepc commented on README.md
> +        { search: ".spectrum-Heading--sizeXXL", replace: "h1" },
Same here to single quote

2023-04-26 16:44 UTC, merged