chore: add vscode recommendations; jira commit tagging
adobe/spectrum-css pull request #1854
Opened 2023-05-09 13:48 UTC by castastrophe

## Description

Add a few VSCode suggestions to help streamline onboarding for new users - I can record a walk-through of how these can facilitate productivity as well. I also included the requisite workspace settings to make setting up these utilities easier.

Added some logic to postfix JIRA information (if it exists in the branch name) to commit messages.

## To-do list
- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).
- [x] This pull request is ready to merge.

2023-06-27 15:34 UTC, castastrophe reviewed
A few possible enhancements

2023-06-27 15:34 UTC, castastrophe commented on .husky/prepare-commit-msg
> +if [ $? -ne 0 ]; then
```suggestion
# If the parse above returns the full branch name, default to the original message
if [ "$ISSUE_KEY" == "$( git rev-parse --abbrev-ref HEAD)" ]; then
```

2023-08-25 14:42 UTC, jawinn requested changes

2023-08-25 14:42 UTC, jawinn commented on .husky/prepare-commit-msg
> +cat $TEMP > $1
I gave this a try with a branch named `css-500-test` and `CSS-500-test2` but did not see it adding the ticket number to the commit messages. I made a commit on each and then looked at the `git log` and did not see any changes to it.

2023-08-25 14:42 UTC, jawinn commented on .vscode/settings.json
> +	"githubIssues.queries": [
👍 Appears to be working. I installed the extension and saw many issues populated when starting to type `#` in a comment to reference an issue.

2023-08-25 14:42 UTC, jawinn commented on .vscode/settings.json
> +	"githubPullRequests.queries": [
👍 Looks good as well. I see these categories appearing with results when I view "GitHub" in the VS Code sidebar.

2023-09-18 13:34 UTC, castastrophe commented
@jawinn I removed the commit message parsing tasks so we can merge this in with just the extensions recommendations 🥳

2023-09-27 12:12 UTC, merged