feat(opacitycheckerboard)!: new component
adobe/spectrum-css pull request #1916
Opened 2023-06-02 21:27 UTC by jenndiaz

## Description

## How and where has this been tested?

- **How this was tested:** 
- **Browser(s) and OS(s) this was tested with:** 

## Screenshots

## To-do list

- [ ] If my change impacts other components, I have tested to make sure they don't break.
- [ ] If my change impacts documentation, I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).
- [ ] I have tested these changes in Windows High Contrast mode.
- [ ] I have updated any relevant storybook stories and templates.
- [ ] If my change(s) include visual change(s), a designer has reviewed and approved those changes.

- [ ] This pull request is ready to merge.

2023-06-06 17:02 UTC, jawinn requested changes
Looking great! Mostly small things noted below.

2023-06-07 17:05 UTC, jenndiaz commented on components/opacitycheckerboard/index.css
> +}
ah yes that makes sense, changed to use inline styling.

2023-06-08 16:03 UTC, jawinn approved these changes

2023-06-09 18:19 UTC, pfulton approved these changes
This looks good @jenndiaz. I know this is a new component, but because it affects several other components, we should talk about the right strategy for getting these shipped to SWC.

Let's discuss on Slack!

2023-07-10 19:01 UTC, pfulton commented
Tracking the implementation here: https://github.com/adobe/spectrum-web-components/pull/3416

2023-07-24 14:19 UTC, merged