feat(dial)!: migrate to use `@adobe/spectrum-tokens`
adobe/spectrum-css pull request #1971
Opened 2023-06-26 14:38 UTC by pfulton

## Description

Migrates the Dial component to use `@adobe/spectrum-tokens` instead of the legacy "vars" packages.

This component does not have an updated spec file from design, nor does it have new tokens defined for it. This is a "DIY migration".

## How and where has this been tested?

- **How this was tested:** 
- **Browser(s) and OS(s) this was tested with:** 

## Screenshots

## To-do list

- [ ] If my change impacts other components, I have tested to make sure they don't break.
- [ ] If my change impacts documentation, I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).
- [ ] I have tested these changes in Windows High Contrast mode.
- [ ] I have updated any relevant storybook stories and templates.
- [ ] If my change(s) include visual change(s), a designer has reviewed and approved those changes.

- [ ] This pull request is ready to merge.

2023-09-22 15:24 UTC, jenndiaz requested changes
Couple of small questions and one issue with the custom token not being applied.

2023-09-22 15:24 UTC, jenndiaz commented on components/tokens/custom-spectrum/custom-large-vars.css
> +  --spectrum-dial-controls-margin: calc(20px / 2);
the margin-inline-start `--spectrum-dial-controls-margin` is not correctly applying to the dial-control, I can see the token come through but it is not being applied. This is causing the dial to not be centered under the label. 

![Screenshot 2023-09-22 at 9 08 35 AM](https://github.com/adobe/spectrum-css/assets/63808889/8bcd0d2a-89c1-4a6c-8d31-dbb3253867fe)

2023-09-22 15:24 UTC, jenndiaz commented on components/dial/stories/template.js
> +// import "../skin.css";
Do we want to go ahead and delete this? 
```suggestion
```

2023-09-22 15:28 UTC, jenndiaz commented on components/dial/index.css
>    margin: 0;
oh I see what's going on with `--spectrum-dial-controls-margin` not being applied, the `margin: 0` is over writing it now. When previously it was pulled out, see below:
``` 
[dir="ltr"] .spectrum-Dial-controls {
    margin-left: var(--spectrum-dial-controls-margin);
}
``` 

Do we need the `margin: 0`? or could we switch to `margin-block: 0`?

2023-09-22 19:56 UTC, jenndiaz commented on components/dial/stories/template.js
> +// import "../skin.css";
pushed a commit that removes this line

2023-09-22 19:58 UTC, jenndiaz commented on components/dial/stories/template.js
> +// import "../skin.css";
I also addressed some weirdness with focus state not quite applying correctly. The component was just appearing white and I found we had a token  `--spectrum-dial-handle-marker-color-mouse-focus` that was not be used that made more sense to use for focused. Without design guidance this change made the most sense.

2023-09-22 20:11 UTC, jenndiaz commented on components/tokens/custom-spectrum/custom-large-vars.css
> +  --spectrum-dial-controls-margin: calc(20px / 2);
more on this here: https://github.com/adobe/spectrum-css/pull/1971#discussion_r1334533780

2023-09-22 20:12 UTC, jenndiaz commented on components/dial/index.css
>    margin: 0;
I went with `margin-block: 0`

2023-09-25 20:12 UTC, jawinn requested changes
This is looking pretty good.

My only questions are around focus and keyboard focus, which also apply to what is in prod. Right now there is no visible focus when tabbing to the dial. On the docs page, `is-keyboardFocused` is applied by the JS there, which does not trigger the `.is-focused` styles (the dark grey visible after click and drag). Rather than using `.is-focused`, should this be using `:focus` or `:focus-visible`? The docs currently are allowing focus on the handle with `tabindex='0'`, which allows those pseudo classes to be activated.

I'm also wondering about disabled showing a hover background color. It does it that way in prod, but it seems odd because it makes it look interactive. And it doesn't seem to match how other components' disabled states behave.

2023-09-26 15:29 UTC, jenndiaz commented on components/dial/index.css
> +  --spectrum-dial-min-max-tick-angle: 45deg;
I also only saw the plural used, I've removed it.

2023-09-26 15:37 UTC, jenndiaz approved these changes

2023-09-27 21:59 UTC, jenndiaz commented
> My only questions are around focus and keyboard focus, which also apply to what is in prod. Right now there is no visible focus when tabbing to the dial. On the docs page, `is-keyboardFocused` is applied by the JS there, which does not trigger the `.is-focused` styles (the dark grey visible after click and drag). Rather than using `.is-focused`, should this be using `:focus` or `:focus-visible`? The docs currently are allowing focus on the handle with `tabindex='0'`, which allows those pseudo classes to be activated.
> 
> I'm also wondering about disabled showing a hover background color. It does it that way in prod, but it seems odd because it makes it look interactive. And it doesn't seem to match how other components' disabled states behave.

@jawinn sorry I missed these comments previously. 

Disabled: 
I agree that the disabled dial should probably not have a hover. I pushed up a commit that removed the hover and active from disabled. I also adjusted the cursor to not display `grab` when the dial is disabled looks like that was intended but the css wasn't in the right spot. 

Didn't get to your focus comment but will look at it tomorrow.

2023-09-28 22:57 UTC, jawinn commented
The updates for disabled and focus look great!

One thing I am noticing is that tab focus disappears for one stop as it appears to go from the handle to the range input itself. I'm not sure if we should put a `tabindex="0"` on the input without some sort of keyboard control behavior/guidelines associated with it? This might also be a good case for `:focus-within`, to at least keep the focus style when the input is focused. To have a single stop in the tab order, we could use `:focus-within` and not have a tabindex on the handle at all, but I don't know if the browser support is enough to use it by default yet (can-i-use says 94.14% global support).

2023-10-11 18:15 UTC, jawinn approved these changes

2023-10-13 16:31 UTC, merged