feat(menu): multi select and switch
adobe/spectrum-css pull request #2152
Opened 2023-09-07 13:31 UTC by mlogsdon18

## Description

This PR adds examples and styling for a multi-select menu option using the Checkbox component, and a multi-select menu option using the Switch component. 

[CSS-245](https://jira.corp.adobe.com/browse/CSS-245)

## How and where has this been tested?

Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the author.

1. Visit the docs site for Menu
- [ ]  Verify that the Multi-Selection example is there and looks like the design
- [ ] Verify that the With Switch example is there and looks like the design

2. Visit the storybook for Menu
- [ ] Verify that the Multiple Selection story looks and functions properly
- [ ] Verify that the With Actiona and the With Value and Actions stories look and function properly

### Regression testing

Validate:

1. A legacy documentation page (such as [accordion](https://pr-###--spectrum-css.netlify.app/accordion.html)), including:

- [ ] The page renders correctly
- [ ] The page is accessible
- [ ] The page is responsive

4. A migrated documentation page (such as [action group](https://pr-###--spectrum-css.netlify.app/actiongroup.html)), including:

- [ ] The page renders correctly
- [ ] The page is accessible
- [ ] The page is responsive

## Screenshots

## To-do list

- [x] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [x] I have updated relevant storybook stories and templates.
- [ ] I have tested these changes in Windows High Contrast mode.

- [ ] If my change impacts **other components**, I have tested to make sure they don't break.
- [x] If my change impacts **documentation**, I have updated the documentation accordingly.

- [ ] ✨ This pull request is ready to merge. ✨

2023-09-11 17:50 UTC, jawinn requested changes
Nice work. One thing I saw that I think needs to be updated is the vertical alignment of the switches. Should they be aligned to the top like the checkboxes are?
![Screenshot 2023-09-11 at 11 24 33 AM](https://github.com/adobe/spectrum-css/assets/965114/e817c873-6994-431d-b8a6-8e6d846ea086)

2023-09-11 18:14 UTC, mlogsdon18 commented
> Nice work. One thing I saw that I think needs to be updated is the vertical alignment of the switches. Should they be aligned to the top like the checkboxes are? ![Screenshot 2023-09-11 at 11 24 33 AM](https://user-images.githubusercontent.com/965114/267104867-e817c873-6994-431d-b8a6-8e6d846ea086.png)

Oh good question. I don't know so I'll shoot that over to design!

2023-09-15 14:11 UTC, pfulton approved these changes

2023-09-15 14:13 UTC, pfulton commented
@najikahalsema Just a heads up that we'll be shipping these new features for Menu. I don't think that there's any changing API here, so we're planning on this being a minor version bump when we eventually merge and release.

2023-09-15 20:14 UTC, merged