fix(picker): picker-quiet-layout
adobe/spectrum-css pull request #2169
Opened 2023-09-14 15:32 UTC by blunteshwar

## Description

Fixed the quiet layout of sp-picker by removing the extra margin

## How and where has this been tested?

Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the author.

### Regression testing

Validate:

1. A legacy documentation page (such as [accordion](https://pr-###--spectrum-css.netlify.app/accordion.html)), including:

- [ ] The page renders correctly
- [ ] The page is accessible
- [ ] The page is responsive

2. A migrated documentation page (such as [action group](https://pr-###--spectrum-css.netlify.app/actiongroup.html)), including:

- [ ] The page renders correctly
- [ ] The page is accessible
- [ ] The page is responsive

## Screenshots

## To-do list

- [x] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [ ] I have updated relevant storybook stories and templates.
- [ ] I have tested these changes in Windows High Contrast mode.

- [ ] If my change impacts **other components**, I have tested to make sure they don't break.
- [ ] If my change impacts **documentation**, I have updated the documentation accordingly.

- [ ] ✨ This pull request is ready to merge. ✨

2023-09-15 17:47 UTC, pfulton reviewed
@blunteshwar I know we talked about this a little during standup on Thursday, but would you mind adding a little more context for this change?

It would be helpful for me to see a few screenshots of the problem(s) you were experiencing in Spectrum Web Components, and then also a before and after screenshot of what's changing here in Spectrum CSS. It doesn't look like our visual regression tests were able to catch the change (which might be a problem on our side).

For reference, I looked at our Figma and Xd specs, and this is the guidance (`quiet` is the second variation in this first image):

<img width="845" alt="Screenshot 2023-09-15 at 1 44 33 PM" src="https://github.com/adobe/spectrum-css/assets/360251/ca4be710-bf94-4c57-aa77-af2004386aed">

<img width="961" alt="Screenshot 2023-09-15 at 1 45 49 PM" src="https://github.com/adobe/spectrum-css/assets/360251/12625b4c-7715-49e4-b817-888cbe646468">

2023-09-18 03:53 UTC, blunteshwar commented
After removing the `margin-block-start: calc(var( --mod-picker-spacing-label-to-picker-quiet, var(--spectrum-picker-spacing-label-to-picker-quiet) ) + 1px);` picker renders correctly
<img width="1728" alt="before" src="https://github.com/adobe/spectrum-css/assets/32033946/b3a2d8d8-1e3c-4d68-bd97-c4b7b44e7033">
<img width="1728" alt="after" src="https://github.com/adobe/spectrum-css/assets/32033946/c7dad3eb-4f89-4369-b931-7bb1482120b7">

2023-09-25 15:39 UTC, blunteshwar commented
@pfulton can you look at this and provide some feedback

2023-09-27 06:33 UTC, Rajdeepc requested changes

2023-09-27 06:33 UTC, Rajdeepc commented on components/picker/index.css
> +
can you remove the whitespace

2023-09-27 07:14 UTC, blunteshwar commented on components/picker/index.css
> +
done!

2023-09-27 20:47 UTC, jenndiaz reviewed
I think this needs more discussion. 
I am understanding the issue as the `margin-block-start` is causing the layout to look incorrect when the label and picker are displayed side by side instead of on top. The most recent design guidance we have does have the negative margin top, like Patrick points out in the screenshots. So this is not added accidentally and removing it doesn't look like the correct solution. 

I do see that the [design page](https://spectrum.adobe.com/page/picker/#Label-position) does say that the label position can be top or side but this did not get displayed on the [figma we have for this component](https://www.figma.com/file/nchxla8gD4CxWYwt9eiRrz/Token-definition-library?type=design&node-id=496-7958&mode=design&t=FN2KHUCZJ8v8Wmeg-0).  

Could we make use of the `--mod-picker-spacing-label-to-picker-quiet` when displayed side by side? 
We could certainly add some guidance to the docs about doing so when displaying side by side. 

Of note, we do have a side by side variant [displayed in storybook](https://opensource.adobe.com/spectrum-css/preview/?path=/story/components-picker--side-label&args=isQuiet:!true).

alternatively I think we'd need to look into adding a side by side variant to our docs site and reach out to design concerning which tokens should be used for this and have separate mark up for a side by side variant that would not apply this margin

2023-09-27 20:56 UTC, jenndiaz commented
actually we do have markup for a side label: https://github.com/adobe/spectrum-css/blob/a0ff7502807b1b6e464a330574fa909024a18bf6/components/picker/index.css#L476

Do we know if the person reporting this issue is using this class?

2023-10-06 09:28 UTC, closed without merging

2023-10-06 09:29 UTC, blunteshwar commented
This issue is being resolved in SWC repository