feat: remove unused theme files
adobe/spectrum-css pull request #2408
Opened 2024-01-05 20:35 UTC by castastrophe

## Description

Currently, when new components are generated, a placeholder file for spectrum and express overrides is generated in a themes folder. If no overrides are necessary, the build system used to require these be committed anyway because it didn't allow missing assets however this was fixed in #2407.

This follows through with deleting any unused theme files from the repository.

## How and where has this been tested?

### Setup

- `yarn build`

### Validation steps

- [ ] Expect no regressions in VRT
- [ ] Expect compiled assets to no longer output empty themes/*.css files

## To-do list

- [x] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [x] I have updated relevant storybook stories and templates.
- [x] If my change impacts **other components**, I have tested to make sure they don't break.
- [x] If my change impacts **documentation**, I have updated the documentation accordingly.
- [x] ✨ This pull request is ready to merge. ✨

2024-01-08 18:27 UTC, pfulton requested changes
This looks good, but one (hopefully small) thing I noticed: the copyright comment block in the `dist` for `components/checkbox/themes/spectrum.css` is getting deleted—the `express` one is still there after compilation. Both `spectrum` and `express` have the comment blocks in their source files.

2024-01-10 13:51 UTC, castastrophe commented
> This looks good, but one (hopefully small) thing I noticed: the copyright comment block in the `dist` for `components/checkbox/themes/spectrum.css` is getting deleted—the `express` one is still there after compilation. Both `spectrum` and `express` have the comment blocks in their source files.

Genuinely boggling because this PR isn't change anything about the build process. 😕

2024-01-10 14:19 UTC, castastrophe commented
@pfulton As a separate commit, I added a workaround to this issue. It's temporary because the build rework will updates this as well but for now, it gets all the spectrum.css assets to retain their copyright.

2024-01-10 21:03 UTC, pfulton approved these changes

2024-01-10 22:25 UTC, merged