fix(tokens): support style-dictionary build in windows env
adobe/spectrum-css pull request #2500
Opened 2024-02-07 17:41 UTC by castastrophe

## Description

When adding an experimental windows-latest run, I found that the style-dictionary compilation was failing pretty terrifically.  This PR aims to fix that by wrapping pathing in path.join so that it can be rendered in a windows-friendly format.

## How and where has this been tested?

Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the author.

### Validation steps

This can be validated via CI which will try to run the tokens build in windows. If the task fails, this PR did not work.

## To-do list

- [x] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [ ] ✨ This pull request is ready to merge. ✨

2024-12-03 21:18 UTC, castastrophe commented
Something to evaluate: https://github.com/storybookjs/storybook/pull/29676/files

2025-03-20 18:50 UTC, castastrophe commented on .github/workflows/build.yml
> +            - name: Capture changes
Doing this as a separate task helps us identify issues more easily in CI

2025-03-25 12:56 UTC, castastrophe commented on tasks/utilities.js
> +			return `${"✗".red}  problem making the ${relativePrint(path.dirname(to), { cwd }).yellow} directory`;
```suggestion
			return Promise.resolve(`${"✗".red}  problem making the ${relativePrint(path.dirname(to), { cwd }).yellow} directory`);
```

2025-03-25 12:56 UTC, castastrophe commented on tasks/utilities.js
> +				return `${"✗".red}  ${relativePrint(from, { cwd }).yellow} could not be copied to ${relativePrint(to, { cwd }).yellow}`;
```suggestion
				return Promise.resolve(`${"✗".red}  ${relativePrint(from, { cwd }).yellow} could not be copied to ${relativePrint(to, { cwd }).yellow}`);
```

2025-04-04 15:43 UTC, jawinn reviewed
I didn't notice any specific issues here and mostly just had questions! Some additional validation instructions and PR description of the various changes would be helpful, as it was a little hard to review all the pieces in a single commit.

I wasn't able to check off the one validation instruction that is there now, as the size of the files have changed slightly, probably due to changes since it was originally written; they were only a few KB different.

2025-04-04 15:43 UTC, jawinn commented on .gitattributes
> +* text=auto eol=lf
It'd be worth noting this line ending config change for all files in the repo.

2025-04-04 15:43 UTC, jawinn commented on postcss.config.js
> +							return join(__dirname, packageParts[1], filePath);
Are we no longer using the dist version of this file? Was this a fix?

2025-04-04 15:43 UTC, jawinn commented on tasks/component-builder.js
> +Promise.all(components.map((componentName) => main({ componentName })));
I'm curious about what this is doing with yargs and the change to run main() on all components at the end of this script. And the same question for the similar change in `tasks/component-reporter.js`.

2025-04-04 15:43 UTC, jawinn commented on tasks/component-compare.js
> +async function fetchPublishedComponent(packageName, {
Thanks for making this into a function.

2025-04-04 15:43 UTC, jawinn commented on tasks/component-compare.js
What are the expected changes to the component compare? I see there are a lot of changes here and want to make sure I can validate them.

2025-04-04 16:43 UTC, marissahuysentruyt reviewed
I think this looks good. As far as I can tell, things are working as they were before. When I checked the file sizes of the `dist/css`, mine didn't exactly line up to your validation notes- is that an issue? They were really close, but not exact - that's all.

<img width="609" alt="Screenshot 2025-04-04 at 12 43 26 PM" src="https://github.com/user-attachments/assets/7378e620-ac67-4c0d-b762-d47b7ff5b8f4" />


My main question is just how else would you like me to validate this, or is there anything else you want me to check? Is there anything that's going to change once this is merged that we should be on the lookout for?

2025-04-04 16:43 UTC, marissahuysentruyt commented on tasks/component-compare.js
> +			warnings.forEach((warning) => cliOutput.push(`${warning}\n`));
I take it some of these changes are just old fashioned refactors? I don't think I should expect to see anything different in my dev console, correct?

2025-04-04 16:43 UTC, marissahuysentruyt commented on tokens/utilities/index.js
> +export { default as JsonSetsFormatter } from "./json-sets-formatter.js";
Do we need both `JsonSetsFormatter` and `DataJsonFormatter`? It looked like we removed `JsonSetsFormatter` from `style-dictionary.config.js`. Was it replaced in favor of `DataJsonFormatter` in the config, or are we missing it in the config?

2025-04-10 21:18 UTC, castastrophe commented on .github/workflows/build.yml
> +            - name: Capture changes
Yeah for sure, the --staged flags ensures we're only diffing the changes detected, meaning those we staged in the previous step. By separating it into its own step instead of including it above, the logs are now easier to read. The more command line steps you run together, the harder it is to distinguish the results in the log output.

2025-04-10 21:20 UTC, castastrophe commented on .github/workflows/development.yml
> +                #       experimental: true
Good point but I did already add a backlog ticket to Jira to cover Windows support so it might not be needed as a todo anymore.

2025-04-10 21:21 UTC, castastrophe commented on package.json
> +		"postcss-preset-env": "^9.5.13",
No I think it just needs a rebase - it's out of sync with the updates on main now.

2025-04-10 21:23 UTC, castastrophe commented on postcss.config.js
> +							return join(__dirname, packageParts[1], filePath);
This was a fix, the filepath includes the dist/css filepath already.

2025-04-10 21:27 UTC, castastrophe commented on tasks/component-builder.js
> +Promise.all(components.map((componentName) => main({ componentName })));
It's a way to help support running these scripts as node entry points vs. calling the functions in the modules. A difference between saying: `node ./tasks/component-builder.js' or having to extract the default method and run it: `node -e 'import('./tasks/component-builder.js').default()`

2025-04-10 21:35 UTC, castastrophe commented on tasks/component-compare.js
Great point, yes this is pulling identical utilities in from the shared utilities resource instead of redefining them. The previous approach rewrote a lot of the same tasks like reporting. It also re-ran the build again manually but the workflow calling this function runs the build first so it's really unnecessary.

2025-04-10 22:03 UTC, castastrophe reviewed
Made a few updates based on this feedback and added more context. Let me know if you want to sync soon and I can talk through any remaining questions as well.

2025-04-10 22:03 UTC, castastrophe commented on tokens/project.json
> -				"deleteOutputPath": false,
The @nxkit tools don't seem to work in Windows _at all_ so moving to the style-dictionary CLI directly really helped improve how far our Windows workflow got. Still not enough to pass but much, much closer.

2025-04-10 22:03 UTC, castastrophe commented on tokens/style-dictionary.config.js
> +import { dirname, join, sep } from "path";
This was rewritten as ESM instead of CJS to support Style Dictionary's breaking change to v4

2025-04-10 22:03 UTC, castastrophe commented on tokens/utilities/index.js
> +export { default as JsonSetsFormatter } from "./json-sets-formatter.js";
Yes great point, we aren't using it.

2025-04-14 17:20 UTC, castastrophe commented on tasks/component-compare.js
> +			warnings.forEach((warning) => cliOutput.push(`${warning}\n`));
No output difference, yes. This method of pushing the output to an array and printing it at the end means we can run in parallel in the script without mixing up the resulting data. Before it was writing immediately to the log so we either had to run them one-by-one or risk mixing up the outputs.

2025-04-14 17:22 UTC, castastrophe commented
> My main question is just how else would you like me to validate this, or is there anything else you want me to check? Is there anything that's going to change once this is merged that we should be on the lookout for?

@marissahuysentruyt It's a tough one to validate yeah because the goal is that everything works the same but now instead of CJS, we're leveraging ESM syntax and the latest release of style-dictionary. It's maybe a subtle performance gain in how fast it runs but overall, hopefully, no significant change.

As for the numbers being off, we probably had a token change since I wrote up the test cases so the file sizes may have updated.

2025-04-16 16:51 UTC, marissahuysentruyt approved these changes
As you noted, this branch seems to be running the same as before. 👍 I don't think I see any glaring issues, so I'm good to approve. Thanks also for the extra context and the few extra commands to help us validate!

2025-04-16 16:51 UTC, marissahuysentruyt commented on tokens/project.json
> +					"tdiff report --old-token-version @adobe/spectrum-tokens@{args.v1} --new-token-version @adobe/spectrum-tokens@{args.v2} --format markdown --output {projectRoot}/dist/tokens-diff.md"
Thanks for this command. The tokens diff is awesome!

<img width="595" alt="Screenshot 2025-04-16 at 12 40 31 PM" src="https://github.com/user-attachments/assets/e5b92605-c38b-481b-af02-13f04aa5b099" />

2025-04-17 13:30 UTC, castastrophe commented on package.json
> +		"stylelint-high-performance-animation": "^1.10.0",
This has been corrected now, thanks!

2025-04-17 21:07 UTC, jawinn requested changes

2025-04-17 21:07 UTC, jawinn commented on .storybook/package.json
> +		"storybook": "^8.6.12",
Looks like a Storybook upgrade got added in here. This newer version still causes all Docs page descriptions to disappear.

2025-04-18 14:20 UTC, castastrophe commented on .storybook/package.json
> +		"storybook": "^8.6.12",
Ah thank you, yes!

2025-04-18 14:22 UTC, castastrophe commented on .storybook/package.json
> +		"storybook": "^8.6.12",
Pushed up that roll-back

2025-04-18 17:56 UTC, jawinn submitted a review, later dismissed

2025-04-18 18:09 UTC, jawinn requested changes

2025-04-18 18:09 UTC, jawinn commented on yarn.lock
> +  version: 8.6.12
It looks like the Storybook updates are still in the yarn.lock file, so the Docs descriptions are still missing on the PR build. Do we need to limit the Storybook version in `main` like we did for `spectrum-two` in #3640, to prevent updated dependencies from getting a version that breaks our docs?

2025-04-18 18:15 UTC, castastrophe commented on yarn.lock
> +  version: 8.6.12
Good point. I've updated to remove the caret in the package.json and regenerated the lockfile.

2025-04-18 18:46 UTC, merged