chore: add format, formatter to apply lint fixes
adobe/spectrum-css pull request #2606
Opened 2024-03-22 21:50 UTC by castastrophe

## Description

## How and where has this been tested?

Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the author.

### Validation steps

### Regression testing

Validate:

1. The documentation pages for at least two other components are still loading, including:

- [ ] The pages render correctly, are accessible, and are responsive.

2. If components have been modified, VRTs have been run on this branch:

- [ ] VRTs have been run and looked at.
- [ ] Any VRT changes have been accepted (by reviewer and/or PR author), or there are no changes.

## Screenshots

## To-do list

- [ ] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [ ] I have updated relevant storybook stories and templates.
- [ ] I have tested these changes in Windows High Contrast mode.
- [ ] If my change impacts **other components**, I have tested to make sure they don't break.
- [ ] If my change impacts **documentation**, I have updated the documentation accordingly.
- [ ] ✨ This pull request is ready to merge. ✨

2024-03-25 14:30 UTC, castastrophe commented
Expected outcome when running `yarn format`:

<img width="518" alt="Screenshot 2024-03-25 at 10 29 32 AM" src="https://github.com/adobe/spectrum-css/assets/1840295/1a1f1f98-c686-400b-a654-b3a94ebf3e1b">

It lists the following components as having "failed" because eslint is catching errors that cannot be "autofixed".

2024-03-25 15:43 UTC, pfulton approved these changes

2024-03-25 16:03 UTC, jawinn requested changes
This looks good to me. I just have one suggestion to stop some errors appearing for the components that do not have the stories folder.

Should there be any concern in this PR with the changes that `format` is applying to the CSS? I noticed some issues with properties being converted to logical properties that shouldn't be. Adjusting that could be a separate PR.

2024-03-26 13:27 UTC, castastrophe commented on nx.json
> +					"eslint --fix {projectRoot}/stories/*.js"
Awesome thank you!

2024-03-26 14:13 UTC, jawinn approved these changes

2024-03-27 19:38 UTC, merged