feat(progressbar): s2 migration
adobe/spectrum-css pull request #2659
Opened 2024-04-12 17:17 UTC by mdt2

## Description

Migrates Progress Bar to Spectrum 2 ([design spec](https://www.figma.com/file/eoZHKJH9a3LJkHYCGt60Vb/S2-token-specs?type=design&node-id=9602-4210&mode=design&t=dE1k2G9oVanenmOD-0)). Includes:

- Updated font sizes
- Updated colors
- WHCM improvement for Static White variant
- Increased Chromatic coverage
- Consolidation of Storybook stories (only Default now and users can use controls to see other variants/states)
- No mods were changed

## How and where has this been tested?

Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the author.

### Validation steps

- [ ] Variants are accessible by controls in Storybook (especially check Static White)
- [ ] Check Chromatic testing preview in Storybook

### Regression testing

Validate:

1. The documentation pages for at least two other components are still loading, including:

- [ ] The pages render correctly, are accessible, and are responsive.

2. If components have been modified, VRTs have been run on this branch:

- [ ] VRTs have been run and looked at.
- [ ] Any VRT changes have been accepted (by reviewer and/or PR author), or there are no changes.

## To-do list

- [x] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [x] I have updated relevant storybook stories and templates.
- [x] I have tested these changes in Windows High Contrast mode.
- [x] If my change impacts **documentation**, I have updated the documentation accordingly.
- [ ] ✨ This pull request is ready to merge. ✨

2024-04-12 17:18 UTC, mdt2 commented on .storybook/decorators/contextsWrapper.js
> +			} else if (args.staticColor === "white" || args.isStaticWhite === "true") {
In the case of Progress Bar, only Static White is supported. I didn't want to make folks use a dropdown in the Storybook controls when there's only one option, so I expanded this to accommodate for that

2024-04-15 15:12 UTC, jawinn requested changes
I tried out all the various options, static white, and high contrast mode, and this is looking great. I see you brought up the side label question with design already.

2024-04-15 15:14 UTC, mdt2 commented on components/progressbar/stories/progressbar.stories.js
> +			type: { name: "string" },
Aha! Thank you 😂 I was like "why is it a string?!"

2024-04-15 16:29 UTC, mdt2 commented on components/progressbar/index.css
>    --spectrum-progressbar-corner-radius: var(--spectrum-corner-radius-100);
Good callout, got confirmation from design that this should be `corner-radius-full`. They also added that to Figma ✨

2024-04-15 19:56 UTC, rise-erpelding approved these changes
This is looking good! The testing preview shows all the variants (including Static White), which match the design spec, which I can also access through the Storybook controls, and WHCM looks good as well!

2024-05-08 20:43 UTC, merged