chore: storybook context application
adobe/spectrum-css pull request #2696
Opened 2024-04-25 15:51 UTC by castastrophe

## Description

Testing pulling out the context update into it's own PR.

## How and where has this been tested?

Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the author.

### Validation steps

### Regression testing

Validate:

1. The documentation pages for at least two other components are still loading, including:

- [ ] The pages render correctly, are accessible, and are responsive.

2. If components have been modified, VRTs have been run on this branch:

- [ ] VRTs have been run and looked at.
- [ ] Any VRT changes have been accepted (by reviewer and/or PR author), or there are no changes.

## Screenshots

## To-do list

- [ ] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [ ] I have updated relevant storybook stories and templates.
- [ ] I have tested these changes in Windows High Contrast mode.
- [ ] If my change impacts **other components**, I have tested to make sure they don't break.
- [ ] If my change impacts **documentation**, I have updated the documentation accordingly.
- [ ] ✨ This pull request is ready to merge. ✨

2024-04-29 18:12 UTC, jawinn requested changes
I tested these changes to `contextsWrapper.js` in the S2 button branch and this does appear to fix the issue with first load of the custom MDX page, along with making sure that all the stories on that page have their gray layer 1 background color coming from the `.spectrum` class 👍 

One place I am not seeing the classes on are the auto "Docs" pages for the components. In particular the first story with controls does not show the background color. Changing the color theme to dark highlights this:
![Screenshot 2024-04-29 at 2 05 25 PM](https://github.com/adobe/spectrum-css/assets/965114/e98df1ef-6710-40de-9711-6412369270aa)
It looks like the container querying may need adjustment to include these auto docs stories? Inspecting, I see that it does still have a container with the `. docs-story` class on it.

2024-04-30 13:31 UTC, castastrophe commented
> It looks like the container querying may need adjustment to include these auto docs stories? Inspecting, I see that it does still have a container with the `.docs-story` class on it.

Great catch @jawinn! Yes, the first container on the page adds a `--primary` postfix to the id that I was missing which was why it was skipping that one box. I've updated it and reviewed several auto docs pages to confirm. Thanks!

2024-04-30 19:33 UTC, jawinn approved these changes
That worked! The auto docs pages have the right backgrounds now. There is just one leftover console.log to remove, then I think this is good to go.

2024-04-30 19:33 UTC, jawinn commented on .storybook/decorators/contextsWrapper.js
> +			console.log({id, roots});
```suggestion

```

2024-05-02 16:01 UTC, merged