fix(textfield + stepper): allow is-disabled to supersede invalid and focus states
adobe/spectrum-css pull request #3012
Opened 2024-08-21 23:54 UTC by cdransf

## Description

- [x] apply `.is-focused`, `:focus` and `is-invalid` states to `textfield` and dependent `stepper` components if `:not(.is-disabled)`. 

**Before:**

![Optional _thumb_12252805](https://github.com/user-attachments/assets/5a74570b-429a-4060-9c57-87f88c5b238d)
![Optional _thumb_12252804](https://github.com/user-attachments/assets/218be866-3e84-44d5-a283-a2e2cfb4f7a4)

**After:**

![Disabled stepper after change (via storybook)](https://github.com/user-attachments/assets/d085924e-85b0-47b1-888d-c8003aea86d3)
![Disabled textfield after change (via storybook)](https://github.com/user-attachments/assets/49e0ed06-ae7c-4321-afee-1ad7aa50d040)

## How and where has this been tested?

Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the author.

### Validation steps

### Regression testing

Validate:

1. The documentation pages for at least two other components are still loading, including:

- [ ] The pages render correctly, are accessible, and are responsive.

2. If components have been modified, VRTs have been run on this branch:

- [ ] VRTs have been run and looked at.
- [ ] Any VRT changes have been accepted (by reviewer and/or PR author), or there are no changes.

## Screenshots

## To-do list

- [x] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [ ] I have updated relevant storybook stories and templates.
- [ ] I have tested these changes in Windows High Contrast mode.
- [ ] If my change impacts **other components**, I have tested to make sure they don't break.
- [ ] If my change impacts **documentation**, I have updated the documentation accordingly.
- [ ] ✨ This pull request is ready to merge. ✨

2024-08-22 00:00 UTC, cdransf commented
✨ I'm not convinced this is the best resolution inasmuch as some other components _do_ support focus states when they're disabled (buttons in particular). Others _do not_, however: checkbox, slider and a few others. ✨

2024-08-30 22:00 UTC, marissahuysentruyt requested changes
@cdransf Thanks for tackling this one! It's quite a tangle.

I think the biggest thing I noticed was the two different color borders for an invalid, focused, then hovered stepper. I don't have a solution to offer quite yet, though.

2024-08-30 22:05 UTC, marissahuysentruyt commented on components/stepper/stories/stepper.test.js
> +			isFocused: true,
This should introduce some VRT regressions since I missed them on my branch.

2024-08-30 22:15 UTC, cdransf commented on components/stepper/index.css
> -			--mod-infield-button-border-color: var(--highcontrast-stepper-border-color-focus-hover, var(--mod-stepper-buttons-border-color-focus-hover, var(--spectrum-stepper-buttons-border-color-focus-hover)
That works — VS Code called it out as undefined, but I'll drop it back in along with a `/* stylelint-disable-next-line spectrum-tools/no-unknown-custom-properties */`.

2024-08-30 22:24 UTC, cdransf commented on components/stepper/index.css
> +	&:hover {
The `:not(.is-disabled)` didn't end up doing anything on that `:hover` state once it was applied to the `spectrum-Stepper` pseudo-class where the border is set. The mod value gets updated but the `border-color` isn't set so it doesn't end up having an impact. I don't think there'd be any harm in keeping it though!

2024-08-30 22:36 UTC, cdransf commented on components/stepper/index.css
> +		&:not(.is-disabled):hover {
Ahhh yep! I am seeing that.

It _does_ look like changing `&:not(.is-disabled):hover` back to `:hover`, restoring the fallback property makes this behave as expected (with the invalid borders back on the interior buttons and the disabled state removing the borders/hover.

```
/* stylelint-disable-next-line spectrum-tools/no-unknown-custom-properties */
--mod-infield-button-border-color: var(--highcontrast-stepper-border-color-focus-hover, var(--mod-stepper-buttons-border-color-focus-hover, var(--spectrum-stepper-buttons-border-color-focus-hover)));
```

<img width="324" alt="Screenshot 2024-08-30 at 3 36 00 PM" src="https://github.com/user-attachments/assets/b87ec7cf-2616-4d44-ae28-e099bc25e7ac">
<img width="367" alt="Screenshot 2024-08-30 at 3 35 53 PM" src="https://github.com/user-attachments/assets/3aa73936-980b-4161-89e5-51f5be927bcf">

2024-08-30 22:46 UTC, cdransf commented on components/textfield/index.css
> +	.is-invalid &:hover:not(.is-disabled) {
This part was strange — the textfield doesn't show the hover styles when disabled _without_ these styles, but the stepper _does_. Adding the `:not(.is-disabled)` resolves the issue in the stepper without impacting the textfield.

2024-08-30 22:48 UTC, cdransf commented on components/textfield/index.css
> +	.is-invalid &:hover:not(.is-disabled) {
Moving the styles to `.spectrum-Stepper-input` causes a regression of the invalid hover state for the textfield. 😵‍💫

2024-08-30 22:50 UTC, cdransf commented on components/stepper/stories/stepper.test.js
> +			isFocused: true,
Thank you for catching this! I totally missed updating those when I added them to the file. 🤦🏼‍♂️

I'll add the `run_vrt` label — I'll push up the changeset as a new commit and then rebase down the road to tidy things up.

2024-09-03 20:27 UTC, rise-erpelding approved these changes
I think this is good to go! I looked over Marissa's previous review and it looks like all of the comments there have been addressed! The VRTs aren't showing anything unexpected, and I couldn't find any edge cases where the border was still looking funny. (But, I will note that the border colors look really wonky/are two different colors for the infield buttons and textfield buttons in forced-colors, especially in dark mode, but this is happening on main too!) Nice work on this!

2024-09-03 21:54 UTC, cdransf commented
> I think this is good to go! I looked over Marissa's previous review and it looks like all of the comments there have been addressed! The VRTs aren't showing anything unexpected, and I couldn't find any edge cases where the border was still looking funny. (But, I will note that the border colors look really wonky/are two different colors for the infield buttons and textfield buttons in forced-colors, especially in dark mode, but this is happening on main too!) Nice work on this!

Thanks so much! 😃 Should we track the issue with the forced colors in a separate ticket? 🎉

2024-09-04 13:47 UTC, rise-erpelding commented
> Thanks so much! 😃 Should we track the issue with the forced colors in a separate ticket? 🎉

It feels like that might be a good idea, but what do you think? For invalid, the stepper looks like this in Windows High Contrast Mode:

<img width="834" alt="image" src="https://github.com/user-attachments/assets/40a319c8-0761-439c-ae38-13c30b72c406">

Once thing I'm noticing is that the infield border color for high contrast [isn't being set except for hover/focus/active](https://github.com/adobe/spectrum-css/blob/main/components/infieldbutton/index.css#L106), but there also aren't a lot of rules being set for WHCM in infield button as we have for other components so that might be something to take a broader look at.

2024-09-04 15:16 UTC, cdransf commented
> > Thanks so much! 😃 Should we track the issue with the forced colors in a separate ticket? 🎉
> 
> It feels like that might be a good idea, but what do you think? For invalid, the stepper looks like this in Windows High Contrast Mode:
>
> One thing I'm noticing is that the infield border color for high contrast [isn't being set except for hover/focus/active](https://github.com/adobe/spectrum-css/blob/main/components/infieldbutton/index.css#L110), but there also aren't a lot of rules being set for WHCM in infield button as we have for other components so that might be something to take a broader look at.

Gotcha! I'd be inclined to hold off and take a broader look down the road in that case — if we handle only this case now we may end up with an inconsistent approach as we address it in each component. 🤔

2024-09-04 16:10 UTC, merged