fix(card, SWC-343): update background-color for card quiet variant
adobe/spectrum-css pull request #3057
Opened 2024-08-30 12:54 UTC by Rajdeepc

… theme

## Description
This PR fixes SWC-343. Updates the `--spectrum-card-preview-background-color` value for card quiet variant in spectrum-two

## How and where has this been tested?

Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the author.

### Validation steps

### Regression testing

Validate:

1. The documentation pages for at least two other components are still loading, including:

- [ ] The pages render correctly, are accessible, and are responsive.

2. If components have been modified, VRTs have been run on this branch:

- [ ] VRTs have been run and looked at.
- [ ] Any VRT changes have been accepted (by reviewer and/or PR author), or there are no changes.

## Screenshots
Previously:

<img width="717" alt="Screenshot 2024-08-30 at 6 23 03 PM" src="https://github.com/user-attachments/assets/3617df00-57b4-4a0e-ab41-989516e744d7">

Updated:
<img width="398" alt="Screenshot 2024-08-30 at 6 24 18 PM" src="https://github.com/user-attachments/assets/6e75b303-867b-4034-b311-69f1efacb435">

## To-do list

- [ ] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [ ] I have updated relevant storybook stories and templates.
- [ ] I have tested these changes in Windows High Contrast mode.
- [ ] If my change impacts **other components**, I have tested to make sure they don't break.
- [ ] If my change impacts **documentation**, I have updated the documentation accordingly.
- [ ] ✨ This pull request is ready to merge. ✨

2024-09-03 20:59 UTC, rise-erpelding approved these changes
This appears to be working as expected on our end!

![image](https://github.com/user-attachments/assets/0d4ecd50-c1dd-48f6-a566-10597ab46864)
![image](https://github.com/user-attachments/assets/45183e17-07b2-408e-9f69-1c200ea1b68a)

2024-09-04 19:55 UTC, jawinn requested changes

2024-09-04 19:55 UTC, jawinn commented on components/card/themes/spectrum-two.css
> +		--spectrum-card-preview-background-color: var(--spectrum-gray-200);
If we're changing this for spectrum-two, shouldn't `spectrum.css` set this back to the Spectrum 1 value of `--spectrum-background-base-color`?

2024-09-06 18:55 UTC, jawinn commented on components/card/themes/spectrum-two.css
> +		--spectrum-card-preview-background-color: var(--spectrum-gray-200);
I see this is updated now, thanks.

2024-09-06 18:55 UTC, jawinn approved these changes

2024-09-09 15:25 UTC, jawinn approved these changes

2024-09-09 16:04 UTC, castastrophe approved these changes

2024-09-09 16:05 UTC, merged