docs(toast): migrate docs to storybook
adobe/spectrum-css pull request #3156
Opened 2024-09-23 23:44 UTC by aramos-adobe

## Description

- Added stories: Action & Wrapping
- Added descriptions for neutral, negative, and informative variants
- Added control for variants
- Added test case for wrapping story 

## How and where has this been tested?

Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the author.

### Validation steps

### Regression testing

Validate:

1. The documentation pages for at least two other components are still loading, including:

- [ ] The pages render correctly, are accessible, and are responsive.

2. If components have been modified, VRTs have been run on this branch:

- [ ] VRTs have been run and looked at.
- [ ] Any VRT changes have been accepted (by reviewer and/or PR author), or there are no changes.

## Screenshots

## To-do list

- [ ] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [ ] I have updated relevant storybook stories and templates.
- [ ] I have tested these changes in Windows High Contrast mode.
- [ ] If my change impacts **other components**, I have tested to make sure they don't break.
- [ ] If my change impacts **documentation**, I have updated the documentation accordingly.
- [ ] ✨ This pull request is ready to merge. ✨

2024-09-26 17:49 UTC, rise-erpelding reviewed
This matches the docs site pretty well and adds in some extra text content from the guidelines, which is really helpful! ❤️ 

Leaving some small suggestions in the comments and also:
I noticed looking over this component that the Docs site and guidelines (and now also the Storybook docs) don't say very much about the Toast variant without a button. In Storybook it's just shown in the Wrapping story. What do you think about showing that a little bit more, either in an existing story or in its own story?

2024-09-26 17:49 UTC, rise-erpelding commented on components/toast/stories/toast.test.js
> +		}
I love that you added this "Wrapping without button" - maybe we could add one more test case without the button with a shorter, non-wrapping label?

2024-09-30 13:57 UTC, rise-erpelding approved these changes
I have one small grammatical nitpick, but otherwise this looks great!

2024-09-30 13:57 UTC, rise-erpelding commented on components/toast/stories/toast.stories.js
> + * They must include text to communicate a message. Write the text as concisely as possible while still being clear about what has happened or is happening.
It's a little unclear what the subject is here, you might exchange "They" for "Toasts" here.

2024-10-01 15:45 UTC, castastrophe requested changes
Looking great!  A few small updates and it's ready to go!

2024-10-01 15:45 UTC, castastrophe commented on components/toast/stories/template.js
> +}, context ) => Container({
```suggestion
export const ToastWrapOptions = (args, context ) => Container({
```

No need to deconstruct the args object here

2024-10-01 15:45 UTC, castastrophe commented on components/toast/stories/template.js
> +		columnGap: "12",
```suggestion
		columnGap: "12px",
```

This will need a unit added.

2024-10-01 15:45 UTC, castastrophe commented on components/toast/stories/template.js
> +}, context ) => Container({
```suggestion
export const ActionTemplate = (args, context ) => Container({
```

2024-10-01 15:45 UTC, castastrophe commented on components/toast/stories/toast.stories.js
> +				defaultValue: { summary: "neutral" },
Nice!  Thanks for adding that default value here.

2024-10-01 15:45 UTC, castastrophe commented on components/toast/stories/toast.stories.js
> + * A toast can have up to one action: [a static white, secondary, outline button.](?path=/docs/components-button--docs#static-white---secondary) This label should be kept concise, and it should only
```suggestion
 * A toast can have up to one action: [a static white, secondary, outline button](?path=/docs/components-button--docs#static-white---secondary). This label should be kept concise, and it should only be used when there’s a direct action available that is related to the toast text.
```

Minor nit to move the period to outside the link.

2024-10-01 15:45 UTC, castastrophe commented on components/toast/stories/toast.test.js
> +		{
Great additions to the test suite!

2024-10-07 16:10 UTC, castastrophe requested changes
Just a few minor updates and it's ready to merge!

2024-10-07 16:10 UTC, castastrophe commented on components/toast/stories/template.js
> +		columnGap: "12",
```suggestion
		columnGap: "12px",
```

2024-10-07 16:10 UTC, castastrophe commented on components/toast/stories/template.js
> +export const ActionTemplate = (args, context ) => Container({
```suggestion
export const ActionTemplate = (args, context) => Container({
```

2024-10-07 16:10 UTC, castastrophe commented on components/toast/stories/toast.stories.js
> + * A toast can have up to one action: [a static white, secondary, outline button.](?path=/docs/components-button--docs#static-white---secondary). This label should be kept concise, and it should only
```suggestion
 * A toast can have up to one action: [a static white, secondary, outline button](?path=/docs/components-button--docs#static-white---secondary). This label should be kept concise, and it should only be used when there’s a direct action available that is related to the toast text.
```

2024-10-08 17:57 UTC, castastrophe approved these changes

2024-10-08 18:15 UTC, merged