docs(actiongroup): migrating docs to storybook
adobe/spectrum-css pull request #3160
Opened 2024-09-24 18:10 UTC by aramos-adobe

## Description

Adding horizontal, vertical, and justified layouts

## How and where has this been tested?

Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the author.

### Validation steps

### Regression testing

Validate:

1. The documentation pages for at least two other components are still loading, including:

- [ ] The pages render correctly, are accessible, and are responsive.

2. If components have been modified, VRTs have been run on this branch:

- [ ] VRTs have been run and looked at.
- [ ] Any VRT changes have been accepted (by reviewer and/or PR author), or there are no changes.

## Screenshots

## To-do list

- [ ] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [ ] I have updated relevant storybook stories and templates.
- [ ] I have tested these changes in Windows High Contrast mode.
- [ ] If my change impacts **other components**, I have tested to make sure they don't break.
- [ ] If my change impacts **documentation**, I have updated the documentation accordingly.
- [ ] ✨ This pull request is ready to merge. ✨

2024-10-01 14:21 UTC, rise-erpelding requested changes
This looks really nice! I really like the way that you've grouped things (with the default, icon-only, quiet variants all together) to keep the number of variants from feeling overwhelming or confusing. I also really like that there are lots of examples (particularly in the sizing) of icons & text together in an action button. And the Overflow section and testing coverage is such a great addition! Overall this is such a huge improvement over the old docs site.

There were two small things I noticed that I think could use improvement, but I'm happy to hear arguments to the contrary:
- We're not showing the emphasized variant for action group. Since we generally do show it for components that have it, and there's a control for it, and we're testing it, it seems like something we ought to be displaying on our Docs page.
- For testing coverage, there are lots of variants, I don't know that every single combination needs to be tested (for instance icon-only compact, or compact quiet, or justified compact, etc.), but one case that I think would be beneficial would be more for vertical action groups, particularly vertical compact.

2024-10-02 18:18 UTC, marissahuysentruyt requested changes
Nice work, this one is coming along!

I think I agree with Rise, that if we're testing the `isEmphasized`, maybe we should showcase it on the docs page. (which I think you actually just pushed up a fix for). I had some similar thoughts around the `isDisabled`. 

I had some comments on adding controls too, so let me know what you think!

2024-10-02 18:18 UTC, marissahuysentruyt commented on components/actiongroup/stories/actiongroup.test.js
>  	],
I think we could add some coverage for the icon-only and text-only options. Tabs has those same 3 options (text-only, text + icon, icon-only), so [we used the `stateData`](https://github.com/adobe/spectrum-css/blob/7e8f6114aef049b82904cebf6a112aa5a2be0feb/components/tabs/stories/tabs.test.js#L86) to cover all of them.

<img width="773" alt="Screenshot 2024-10-02 at 1 59 51 PM" src="https://github.com/user-attachments/assets/72a350e8-0b88-4ab8-bb3f-a4bba7b0617a">

2024-10-02 18:18 UTC, marissahuysentruyt commented on components/actiongroup/stories/template.js
> +					size: size
Ohhh great catch here! 👏👏👏

2024-10-02 18:18 UTC, marissahuysentruyt commented on components/actiongroup/stories/actiongroup.stories.js
> + * When space is limited in an action group, there are 2 options for the group's overflow behavior: wrap or collapse. By default, an action group is set to wrap, meaning that the action buttons insid
Do you think we need backticks or something for the 'More (...)' part? I don't think it'd be recommended to use quotes, but maybe backticks would draw attention to that. Or we could wrap it in `**`/a `<strong>` tag like it is on the guidance site? Any thoughts on that?

2024-10-02 18:18 UTC, marissahuysentruyt commented on components/actiongroup/stories/actiongroup.stories.js
>  	title: "Action group",
oooo! What do you think about adding an icon-only control? Similar to [tabs](https://github.com/adobe/spectrum-css/blob/7e8f6114aef049b82904cebf6a112aa5a2be0feb/components/tabs/stories/tabs.stories.js#L74)? That would give users the option to see their icon-only action buttons. 

<img width="589" alt="Screenshot 2024-10-02 at 2 12 43 PM" src="https://github.com/user-attachments/assets/9cf5ac44-62bf-457b-a027-b82f0e352505">

2024-10-03 13:35 UTC, rise-erpelding approved these changes
I can see lots of those extra suggestions were added--this looks great!

2024-10-03 19:06 UTC, marissahuysentruyt requested changes
Thanks for making those updates! I found a few more updates I think we should make 😊

2024-10-03 19:06 UTC, marissahuysentruyt commented on components/actiongroup/stories/actiongroup.stories.js
> +				category: "Advanced",
Does `iconOnly` belong in "Advanced", or is it just "Component?" I don't really know or have much of an opinion, just curious. Some other components that have some similar icon controls, like contextual help, tabs, and menu (technically menu item) have it in "Component" or "Content." Just a thought for you!

2024-10-08 13:18 UTC, marissahuysentruyt approved these changes
@aramos-adobe thanks for making all of the updates! This looks fantastic! I think all of the additions gives users so much context and explanation for this component now, in comparison to the current docs site! 

I did a quick check of the CHANGELOG and I think the migration guide is all included, so boom- approved!

2024-10-08 14:49 UTC, merged