fix(coachindicator): adds 'static white', deprecates light/dark
adobe/spectrum-css pull request #3266
Opened 2024-10-18 14:20 UTC by 5t3ph

## Description

Per [feedback from PJ](https://adobedesign.slack.com/archives/GEN034MAS/p1729092256236909) on expected variants for Coach indicator, marks "light" and "dark" as deprecated for S2, and adds "static white".

[According to Spectrum stats](https://awesome.adproto.com/spectrum-metric-web-app-main/#/@spectrum-web-components/components), it seems this component is very low usage overall and also that the default variant is the only one in use in products, if at all.

## How and where has this been tested?

Locally in Storybook.

### Validation steps

In Storybook, find the "Coach indicator" docs page to review the added "Static white" story.

### Regression testing

Validate:

1. The documentation pages for at least two other components are still loading, including:

- [x] The pages render correctly, are accessible, and are responsive.

2. If components have been modified, VRTs have been run on this branch:

- [ ] VRTs have been run and looked at.
- [ ] Any VRT changes have been accepted (by reviewer and/or PR author), or there are no changes.

## Screenshots

<img width="943" alt="image" src="https://github.com/user-attachments/assets/81f88693-2b90-4a58-938c-a0db261f2319">

## To-do list

- [x] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [x] I have updated relevant storybook stories and templates.
- [x] I have tested these changes in Windows High Contrast mode.
- [x] If my change impacts **other components**, I have tested to make sure they don't break.
- [x] If my change impacts **documentation**, I have updated the documentation accordingly.
- [ ] ✨ This pull request is ready to merge. ✨

2024-10-21 14:28 UTC, rise-erpelding requested changes
The CSS for coach indicator and tokens looks great! I made a couple of small suggestions for the Storybook side of things to better align with how we've done other components.

2024-10-21 15:34 UTC, 5t3ph commented on tokens/custom-spectrum/custom-vars.css
> +	--spectrum-docs-static-white-background-color: rgb(15, 121, 125);
I'm not sure why this indentation is happening on these token files, it's not like that locally :(

2024-10-21 15:35 UTC, 5t3ph commented on components/coachindicator/stories/coachindicator.stories.js
> +			options: ["default", "dark", "light", "staticWhite"],
@rise-erpelding thanks for sharing, I've updated as you suggested!

2024-10-21 21:07 UTC, rise-erpelding approved these changes
Looks great!

2024-10-22 16:00 UTC, cdransf approved these changes

2024-10-22 16:33 UTC, merged