docs(textarea): add corrected guidelines link and rootClass
adobe/spectrum-css pull request #3326
Opened 2024-10-25 14:37 UTC by marissahuysentruyt

- adds a spectrum-Textarea rootClass to textarea component. It doesn't have any styles, is strictly an addition and doesn't overwrite/interfere with the textfield component in the text area template.
- adds an additional spectrum object to contain the text area guidance link

## Description

## How and where has this been tested?

Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the author.

### Validation steps

### Regression testing

Validate:

1. The documentation pages for at least two other components are still loading, including:

- [ ] The pages render correctly, are accessible, and are responsive.

2. If components have been modified, VRTs have been run on this branch:

- [ ] VRTs have been run and looked at.
- [ ] Any VRT changes have been accepted (by reviewer and/or PR author), or there are no changes.

## Screenshots

## To-do list

- [ ] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [ ] I have updated relevant storybook stories and templates.
- [ ] I have tested these changes in Windows High Contrast mode.
- [ ] If my change impacts **other components**, I have tested to make sure they don't break.
- [ ] If my change impacts **documentation**, I have updated the documentation accordingly.
- [ ] ✨ This pull request is ready to merge. ✨

2024-10-28 17:23 UTC, castastrophe requested changes

2024-10-28 17:23 UTC, castastrophe commented on components/textfield/package.json
> +			"rootClass": "spectrum-Textarea"
```suggestion
			"rootClass": "spectrum-Textfield--multiline"
```

I guess technically this is the "rootClass" being used by the text area right?

2024-10-28 17:23 UTC, castastrophe commented on components/textfield/stories/textarea.stories.js
> +		rootClass: "spectrum-Textarea",
This class does not exist in the system. Maybe `.spectrum-Textfield--multiline`?

2024-10-30 13:30 UTC, castastrophe commented
@marissahuysentruyt I wasn't sure about this test case, is this still accurate with the --sizeM at the end?

> When inspecting any of the text area templates, the additional spectrum-Textfield--multiline--sizeM class has been added to the parent container. (this has no other styles, besides the styles for spectrum-Textfield--multiline)

2024-10-31 19:50 UTC, marissahuysentruyt commented on components/textfield/stories/textarea.template.js
> -		typeof size !== "undefined" ? `${rootClass}--size${size.toUpperCase()}` : null,
This seemed to be adding an additional `.spectrum-Textfield--multiline--sizeM` once I started editing the text area `rootClass`. We don't have sizing for `.spectrum-Textfield--multiline`/text area, so does this make sense?

2024-11-01 16:02 UTC, castastrophe approved these changes

2024-11-05 17:41 UTC, cdransf approved these changes

2024-11-05 22:07 UTC, merged