feat(progress-circle): migrating s2 tokens
adobe/spectrum-css pull request #3380
Opened 2024-11-10 20:11 UTC by aramos-adobe

## Description

### S2 migration for progress circle
Changed from using border styles to `stroke-*` styles and attributes. The svg element allows for `stroke-linecap` to enable to the rounded path. 

### Animation

`@keyframes spectrum-dashoffset-animation`:
This animation was created by React Spectrum and used to keep the same speed and bezier curve.

### Removed styles & mods

`--spectrum-progress-circle-track-border-color-over-background`
`--spectrum-progress-circle-fill-border-color-over-background`
`--spectrum-progress-circle-track-border-style`
`--spectrum-progress-circle-track-border-style`
`--highcontrast-progress-circle-track-border-style`
`--mod-progress-circle-track-border-style`
`--spectrum-progress-circle-track-border-style`

### Validation steps
  1. Open the storybook doc for the progress circle component:
    - [x] Choose static color options to see correct tokens applied
    - [x] Toggle indeterminate option see the animation
    - [x] Range slider to see the flow of progress track fill

### Regression testing

Validate:

1. The documentation pages for at least two other components are still loading, including:

- [ ] The pages render correctly, are accessible, and are responsive.

2. If components have been modified, VRTs have been run on this branch:

- [ ] VRTs have been run and looked at.
- [ ] Any VRT changes have been accepted (by reviewer and/or PR author), or there are no changes.

## Screenshots

## To-do list

- [ ] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [ ] I have updated relevant storybook stories and templates.
- [ ] I have tested these changes in Windows High Contrast mode.
- [ ] If my change impacts **other components**, I have tested to make sure they don't break.
- [ ] If my change impacts **documentation**, I have updated the documentation accordingly.
- [ ] ✨ This pull request is ready to merge. ✨

2024-11-19 19:12 UTC, marissahuysentruyt requested changes
Woo- love the updated styles. I think I wrapped my head around the animation stuff, but if anything is confusing, let's pair! 🍐 

A couple of other thoughts I wasn't sure where to put: 
- Cassondra separated some of nested components in the `s2-foundations-redux` branch. For instance, progress bar and meter _were_ nested together, but now they're totally separate (https://github.com/adobe/spectrum-css/tree/s2-foundations-redux/components/meter). Same thing with form being separated from field label. You may have already know, but is there a way in this branch we can prep for infield progress circle being separate from progress circle? Or maybe we leave our comment/note/Jira ticket for ourselves? Should these 2 components be nested like they are now, or should they be separated into different component directories? 

- Let's just fix the typo in the file names. (infield-progress_cirlce_ > progresscircle)

2024-11-20 04:36 UTC, aramos-adobe commented on components/progresscircle/index.css
> +			1s cubic-bezier(0.25, 0.1, 0.25, 1.3) infinite 0s spectrum-dashoffset-animation;
Mmmmm!! Good call out on the bezier curve. I removed it and it moves the way React Spectrum's does now.

2024-11-21 21:22 UTC, aramos-adobe commented on components/progresscircle/animation.css
> +	animation: 1s infinite linear spectrum-fill-mask-1;
It does absolutely nothing so I'm removing them both

2025-01-08 21:38 UTC, marissahuysentruyt requested changes
Your rebase cleaned this up so nice! It's looking good, but I do have some questions for you: 

Just wanted to be sure- the `corner-radius-full` token for the fill isn't used correct? Because we're using the `stroke-linecap` attribute? I saw it in the Figma file, but didn't see it used in a quick search of the CSS file. But I'm pretty sure that's why.

There's the changes in `progress-bar.stories.js` and `tooltip.stories.js`. I vote we revert those and I'll get a bug branch going to fix those pages. 

The test files are here! Would you add the static black test case? 
```
// progresscircle.test.js
...
{
			testHeading: "Static white",
			staticColor: "white",
		},
{
			testHeading: "Static black",
			staticColor: "black",
		},
...
```

2025-01-08 21:38 UTC, marissahuysentruyt commented on components/progressbar/stories/progressbar.stories.js
There's actually a bug in the `spectrum-two` branch: https://github.com/adobe/spectrum-css/blob/dd96363745d39e200cfea84092903fcd53c340b3/components/progressbar/stories/template.js#L15

The progress bar's arg `isStaticWhite` should actually be `staticColor`. Regardless, I think these changes with the indeterminate group and template should be removed.

2025-01-08 21:38 UTC, marissahuysentruyt commented on components/progresscircle/stories/progresscircle.stories.js
> +import { isIndeterminate, size } from "@spectrum-css/preview/types";
Let's get the `staticColor` import back! Yay!

`import { isIndeterminate, size, staticColor } from "@spectrum-css/preview/types";`

That means we can basically revert these `staticColor` control changes as well. In the controls, we should just be able to do `staticColor`, since we need both the black and white options now too. 👍 

<img width="132" alt="Screenshot 2025-01-08 at 4 14 42 PM" src="https://github.com/user-attachments/assets/84c55955-931e-46c5-a9e5-b4166869affb" />

2025-01-08 21:38 UTC, marissahuysentruyt commented on components/progresscircle/stories/progresscircle.stories.js
> +};
Now that we do have the `Sizing()` function, what do you tihnk about using it for both of these static black stories? Instead of binding to `Template()`, bind to `Sizing()` like the static white stories? 

```suggestion
export const StaticBlackDeterminate = Sizing.bind({});
StaticBlackDeterminate.tags = ["!dev"];
StaticBlackDeterminate.storyName = "Static black, default";
StaticBlackDeterminate.args = {
	staticColor: "black",
	isIndeterminate: false,
};
StaticBlackDeterminate.parameters = {
	chromatic: { disableSnapshot: true },
};

export const StaticBlackIndeterminate = Sizing.bind({});
StaticBlackIndeterminate.tags = ["!dev"];
StaticBlackIndeterminate.storyName = "Static black, indeterminate";
StaticBlackIndeterminate.args = {
	staticColor: "black",
	isIndeterminate: true,
};
StaticBlackIndeterminate.parameters = {
	chromatic: { disableSnapshot: true },
};
```

There's nothing wrong with what you have, it's just the odd ones out of the bunch on the docs page.

<img width="1058" alt="Screenshot 2025-01-08 at 4 17 36 PM" src="https://github.com/user-attachments/assets/743b2943-72e6-4b8b-924e-d8ce3c97e638" />

2025-01-08 21:38 UTC, marissahuysentruyt commented on components/tooltip/stories/tooltip.stories.js
Similar to my progress bar comment, I think we should revert these changes completely. As far as I can tell, they shouldn't be related to your progress circle work, and there's a separate bug with tooltip (not having the `variant = "neutral",` arg in it's template).

2025-01-08 21:38 UTC, marissahuysentruyt commented on components/progresscircle/stories/template.js
> +	` : Template(args)}
We have the test files after the `spectrum-two` update, so we don't even need this anymore! 🥳🥳🥳🥳

2025-01-09 15:27 UTC, marissahuysentruyt requested changes
I went through the CSS this morning and things are looking really good! I found we were missing the `track-color` token, but overall, I really love all the animation code we were able to remove! Nice work 😄 

I did have a question about the animation (and this is a real nit-pick, so feel free to disregard if you are happy with the fill animation!). Is it "stopping" at the top of the progress circle just before the animation loops? I can't tell if that's my eyes playing tricks on me or if there's really a pause. 

https://github.com/user-attachments/assets/15812014-8b4e-4c9c-b879-4ad97f7d2081

Other than that, my final questions are really regarding high contrast mode.

2025-01-09 15:27 UTC, marissahuysentruyt commented on components/progresscircle/index.css
> -	}
I think we need to revisit the high contrast mode. The only reason I started looking into this was because I saw no track for the staticBlack stories. So I pulled it up in AssistivLabs and noticed that there's just some discrepancies where the the staticBlack stories still has its transparent-black track (so you can't really visually see it), the default/sizing/indeterminate stories have a brighter white track (which I think is the gray-200), and then staticWhite has a different track color (the transparent-white token). You can see all 3 different track colors in this screenshot:

<img width="1037" alt="Screenshot 2025-01-09 at 9 47 59 AM" src="https://github.com/user-attachments/assets/2c0c1ac2-48e3-49b2-8171-d690518a7316" />

I don't really have an answer for this besides asking in the channel.

2025-01-09 15:27 UTC, marissahuysentruyt commented on components/progresscircle/index.css
> -	}
I was thinking maybe we could emulate what progress bar is doing with a `--highcontrast-progresscircle-track-color: ButtonFace;`, but I think that would require additional SVG work in order to get a "border" on the track? That `ButtonFace` color is coming through, but it's just really low contrast.

<img width="678" alt="Screenshot 2025-01-09 at 10 12 14 AM" src="https://github.com/user-attachments/assets/66cc5264-e61a-4305-a0e0-d0f2c12ffc67" />
<img width="236" alt="Screenshot 2025-01-09 at 10 11 55 AM" src="https://github.com/user-attachments/assets/88b3513d-7292-47e7-a341-1bacb9172698" />

2025-01-09 15:27 UTC, marissahuysentruyt commented on components/progresscircle/index.css
>  	/* circle unfilled border color */
Should `--spectrum-progress-circle-track-border-color` be aliased to `--spectrum-track-color` instead of the global, gray-200? When this goes to design review, are they going to be looking for `track-color` since that's in Figma? It also looks like `track-color` is actually gray-300 anyways.

<img width="339" alt="Screenshot 2025-01-09 at 10 19 39 AM" src="https://github.com/user-attachments/assets/e20a5f2f-e7d3-4569-9b17-ec1f5c5c77d7" />

2025-01-09 15:27 UTC, marissahuysentruyt commented on components/progresscircle/index.css
> -	}
I looked back at the static white progress circle, in WHCM, and this is what it looks like on `spectrum-two`. I feel like that's probably what we want to try to recreate, particularly with the borders. What do you think?

<img width="270" alt="Screenshot 2025-01-09 at 10 24 33 AM" src="https://github.com/user-attachments/assets/a8ea77c8-291e-4a85-9591-16bcf8b3237f" />

2025-01-13 17:05 UTC, aramos-adobe commented on components/progresscircle/index.css
> -	}
@marissahuysentruyt I've added the borders for WHCM. For indeterminate mode, the borders are not there. Speaking with design, as of right now the track is not needed for indeterminate just to show the loading state. But for progress the track is necessary.

2025-01-23 16:58 UTC, marissahuysentruyt commented on components/progresscircle/index.css
> +	stroke: var(--highcontrast-progressbar-track-color, var(--mod-progress-circle-track-border-color, var(--spectrum-progress-circle-track-border-color)));
I think we need to delete this progress bar custom property in favor of a `--highcontrast-progress-circle-track-border-color` instead.

2025-01-23 20:50 UTC, marissahuysentruyt approved these changes
Let's get that second approval and get this thing merrggedd! It looks awesome. Thanks for wading through all of my comments and ramblings!

![michael-scott-disco-coffee](https://github.com/user-attachments/assets/ec99638f-1a1a-437e-adce-d68a8de913cb)

2025-01-24 19:49 UTC, merged