feat(coachmark): S2 migration
adobe/spectrum-css pull request #3412
Opened 2024-11-21 19:37 UTC by cdransf

## Description

---
"@spectrum-css/coachmark": major
---

# S2 coachmark migration

This migrates the `coachmark` component to S2. Custom properties have been remapped per the design spec.

| Before                                     | After                                           |
| ------------------------------------------ | ----------------------------------------------- |
| --spectrum-sans-serif-font                 | --spectrum-title-sans-serif-font-family         |
| --spectrum-heading-serif-font-style        | --spectrum-title-serif-font-style               |
| --spectrum-heading-sans-serif-font-weight  | --spectrum-title-sans-serif-font-weight         |
| --spectrum-coach-mark-title-size           | --spectrum-coach-mark-title-font-size           |
| --spectrum-heading-line-height             | --spectrum-title-line-height                    |
| --spectrum-coach-mark-body-size            | --spectrum-coach-mark-body-font-size            |
| --spectrum-sans-serif-font                 | --spectrum-body-sans-serif-font-family          |
| --spectrum-body-sans-serif-font-style      | --spectrum-body-serif-font-style                |
| --spectrum-coach-mark-pagination-body-size | --spectrum-coach-mark-pagination-body-font-size |

### Validation steps

1. Open the URL for the PR.
2. Navigate to the `coachmark` component and verify no regressions have occurred.

**Note: the new `font-family` tokens set the font to `Adobe Clean` but `Adobe Clean` is not loading on the branch created from the `spectrum-two` base branch.**

### Regression testing

Validate:

1. The documentation pages for at least two other components are still loading, including:

- [x] The pages render correctly, are accessible, and are responsive.

4. If components have been modified, VRTs have been run on this branch:

- [ ] VRTs have been run and looked at.
- [ ] Any VRT changes have been accepted (by reviewer and/or PR author), or there are no changes.

## To-do list

- [x] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [ ] I have updated relevant storybook stories and templates.
- [ ] I have tested these changes in Windows High Contrast mode.
- [ ] If my change impacts **other components**, I have tested to make sure they don't break.
- [ ] If my change impacts **documentation**, I have updated the documentation accordingly.
- [x] ✨ This pull request is ready to merge. ✨

2024-11-22 16:52 UTC, jawinn requested changes
I'm seeing a few things on the design not represented yet.

**Line-height changes**
I see body and pagination in the S2 specs marked as using `line-height-200`. I don't see the CSS using this token.
<img width="192" alt="Screenshot 2024-11-22 at 10 55 57 AM" src="https://github.com/user-attachments/assets/2c2881c5-3c0c-4b51-b9ae-b5d4100abcd1">

**Keyboard shortcut**
I don't see this new feature represented yet in our Docs examples or styles or controls. Does design need to define tokens for these keyboard shortcut elements on the specs?
<img width="352" alt="Screenshot 2024-11-22 at 11 22 12 AM" src="https://github.com/user-attachments/assets/11954404-fff5-45cb-8c2e-cf1ef54bbaf1">
<img width="233" alt="Screenshot 2024-11-22 at 11 20 35 AM" src="https://github.com/user-attachments/assets/02af392a-501a-40e6-ae73-6db291c77b02">
<img width="153" alt="Screenshot 2024-11-22 at 11 20 18 AM" src="https://github.com/user-attachments/assets/68085763-850e-4212-a80d-cb3dbb39858c">

**4:3 and 16:19 image**
The design shows an example of images at both of these aspect ratios, that we should demonstrate in our docs and maybe have a control for. I'm not exactly sure how this ties in with the sizing of the image and tokens.

**Wait on popover to finalize?**
This component is heavily reliant on popover, which has its S2 migration in progress and has been discussing and updating some items related to coachmark (#3365). So it may be worth waiting on that to merge before final review of its design.

2024-11-22 19:41 UTC, cdransf commented
> I'm seeing a few things on the design not represented yet.
> 
> **Line-height changes** I see body and pagination in the S2 specs marked as using `line-height-200`. I don't see the CSS using this token. <img alt="Screenshot 2024-11-22 at 10 55 57 AM" width="192" src="https://private-user-images.githubusercontent.com/965114/389009688-2c2881c5-3c0c-4b51-b9ae-b5d4100abcd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMDEyOTMsIm5iZiI6MTczMjMwMDk5MywicGF0aCI6Ii85NjUxMTQvMzg5MDA5Njg4LTJjMjg4MWM1LTNjMGMtNGI1MS1iOWFlLWI1ZDQxMDBhYmNkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxODQzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODY3NWUzNTc1MTkyMjUyZjZkNmIyYWQ3MzI0M2NjYjQzZDg2YzhlN2IyYjUxZGQ4MjExZTg1N2E0ZWU5ZTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7vm3NKGWJlrBUMF7Puu0_oaVNd2Z6I5AtAUSqx6uXGc">
> 
> **Keyboard shortcut** I don't see this new feature represented yet in our Docs examples or styles or controls. Does design need to define tokens for these keyboard shortcut elements on the specs? <img alt="Screenshot 2024-11-22 at 11 22 12 AM" width="352" src="https://private-user-images.githubusercontent.com/965114/389016095-11954404-fff5-45cb-8c2e-cf1ef54bbaf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMDEyOTMsIm5iZiI6MTczMjMwMDk5MywicGF0aCI6Ii85NjUxMTQvMzg5MDE2MDk1LTExOTU0NDA0LWZmZjUtNDVjYi04YzJlLWNmMWVmNTRiYmFmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxODQzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTg0OGY0MGE5ZWIwMWNiMTY4OTc5OTczZTIzYzc5ZTc0OGVkODc0ZGFkOGMzNTVhMzJlOGUzYjk1MDYwM2VkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uKHjVJ6GFZU-6pUoNjUyq7gq4-knm2LPD77Hs9J5G4c"> <img alt="Screenshot 2024-11-22 at 11 20 35 AM" width="233" src="https://private-user-images.githubusercontent.com/965114/389016102-02af392a-501a-40e6-ae73-6db291c77b02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMDEyOTMsIm5iZiI6MTczMjMwMDk5MywicGF0aCI6Ii85NjUxMTQvMzg5MDE2MTAyLTAyYWYzOTJhLTUwMWEtNDBlNi1hZTczLTZkYjI5MWM3N2IwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxODQzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDJjMmUwYjIxNDI2OTcwZWI0ODJiN2JjYWI3Yzg3YmQxYjExNTM1YTJkZTI2MWNhOWUxMWQwMDM2NzUyMGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.O8MfwVE4wA_4hIferjj0N9T4rvC4AGodoz0wQ-3rVtI"> <img alt="Screenshot 2024-11-22 at 11 20 18 AM" width="153" src="https://private-user-images.githubusercontent.com/965114/389016106-68085763-850e-4212-a80d-cb3dbb39858c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMDEyOTMsIm5iZiI6MTczMjMwMDk5MywicGF0aCI6Ii85NjUxMTQvMzg5MDE2MTA2LTY4MDg1NzYzLTg1MGUtNDIxMi1hODBkLWNiM2RiYjM5ODU4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxODQzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjFmNTQ4ODUwZmQ3NDlmYWUxMjhkY2RiNTUyZmFjYTg5YmJkODhjOWIyYzQzNDFkZWM4MzVhMGMyYzY5YzM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HZbJDp5KA9sNd7PvcNQS5-opR7dAVSQVsgjcnSBYuls">
> 
> **4:3 and 16:19 image** The design shows an example of images at both of these aspect ratios, that we should demonstrate in our docs and maybe have a control for. I'm not exactly sure how this ties in with the sizing of the image and tokens.
> 
> **Wait on popover to finalize?** This component is heavily reliant on popover, which has its S2 migration in progress and has been discussing and updating some items related to coachmark (#3365). So it may be worth waiting on that to merge before final review of its design.

Awesome catches! I updated the line-height and font tokens. I marked this blocked pending the popover work and started a thread about the image implementation (one token includes `-minimum-` which seems _odd_ semantically.

2024-11-27 17:28 UTC, cdransf commented
> > I'm seeing a few things on the design not represented yet.
> > **Line-height changes** I see body and pagination in the S2 specs marked as using `line-height-200`. I don't see the CSS using this token. <img alt="Screenshot 2024-11-22 at 10 55 57 AM" width="192" src="https://private-user-images.githubusercontent.com/965114/389009688-2c2881c5-3c0c-4b51-b9ae-b5d4100abcd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMDEyOTMsIm5iZiI6MTczMjMwMDk5MywicGF0aCI6Ii85NjUxMTQvMzg5MDA5Njg4LTJjMjg4MWM1LTNjMGMtNGI1MS1iOWFlLWI1ZDQxMDBhYmNkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxODQzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODY3NWUzNTc1MTkyMjUyZjZkNmIyYWQ3MzI0M2NjYjQzZDg2YzhlN2IyYjUxZGQ4MjExZTg1N2E0ZWU5ZTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7vm3NKGWJlrBUMF7Puu0_oaVNd2Z6I5AtAUSqx6uXGc">
> > **Keyboard shortcut** I don't see this new feature represented yet in our Docs examples or styles or controls. Does design need to define tokens for these keyboard shortcut elements on the specs? <img alt="Screenshot 2024-11-22 at 11 22 12 AM" width="352" src="https://private-user-images.githubusercontent.com/965114/389016095-11954404-fff5-45cb-8c2e-cf1ef54bbaf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMDEyOTMsIm5iZiI6MTczMjMwMDk5MywicGF0aCI6Ii85NjUxMTQvMzg5MDE2MDk1LTExOTU0NDA0LWZmZjUtNDVjYi04YzJlLWNmMWVmNTRiYmFmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxODQzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTg0OGY0MGE5ZWIwMWNiMTY4OTc5OTczZTIzYzc5ZTc0OGVkODc0ZGFkOGMzNTVhMzJlOGUzYjk1MDYwM2VkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uKHjVJ6GFZU-6pUoNjUyq7gq4-knm2LPD77Hs9J5G4c"> <img alt="Screenshot 2024-11-22 at 11 20 35 AM" width="233" src="https://private-user-images.githubusercontent.com/965114/389016102-02af392a-501a-40e6-ae73-6db291c77b02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMDEyOTMsIm5iZiI6MTczMjMwMDk5MywicGF0aCI6Ii85NjUxMTQvMzg5MDE2MTAyLTAyYWYzOTJhLTUwMWEtNDBlNi1hZTczLTZkYjI5MWM3N2IwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxODQzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDJjMmUwYjIxNDI2OTcwZWI0ODJiN2JjYWI3Yzg3YmQxYjExNTM1YTJkZTI2MWNhOWUxMWQwMDM2NzUyMGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.O8MfwVE4wA_4hIferjj0N9T4rvC4AGodoz0wQ-3rVtI"> <img alt="Screenshot 2024-11-22 at 11 20 18 AM" width="153" src="https://private-user-images.githubusercontent.com/965114/389016106-68085763-850e-4212-a80d-cb3dbb39858c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMDEyOTMsIm5iZiI6MTczMjMwMDk5MywicGF0aCI6Ii85NjUxMTQvMzg5MDE2MTA2LTY4MDg1NzYzLTg1MGUtNDIxMi1hODBkLWNiM2RiYjM5ODU4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxODQzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjFmNTQ4ODUwZmQ3NDlmYWUxMjhkY2RiNTUyZmFjYTg5YmJkODhjOWIyYzQzNDFkZWM4MzVhMGMyYzY5YzM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HZbJDp5KA9sNd7PvcNQS5-opR7dAVSQVsgjcnSBYuls">
> > **4:3 and 16:19 image** The design shows an example of images at both of these aspect ratios, that we should demonstrate in our docs and maybe have a control for. I'm not exactly sure how this ties in with the sizing of the image and tokens.
> > **Wait on popover to finalize?** This component is heavily reliant on popover, which has its S2 migration in progress and has been discussing and updating some items related to coachmark (#3365). So it may be worth waiting on that to merge before final review of its design.
> 
> Awesome catches! I updated the line-height and font tokens. I marked this blocked pending the popover work and started a thread about the image implementation (one token includes `-minimum-` which seems _odd_ semantically.

Spoke with design and it sounds like the minimum token is the minimum dimension for the coach mark image and 4:3 is not a strict max. This is the current state:

```css
.spectrum-CoachMark-image-wrapper {
  block-size: var(--mod-coachmark-media-height, var(--spectrum-coachmark-media-height));
  min-block-size: var(--mod-coachmark-media-min-height, var(--spectrum-coachmark-media-min-height));
...
}
```

2024-12-17 19:50 UTC, cdransf commented on components/coachmark/index.css
>  	--spectrum-coachmark-step-font-weight: var(--spectrum-body-medium-font-weight);
🤫

2024-12-19 21:06 UTC, jawinn requested changes
The line-height looks good, and thanks for finding out the intentions on the 4:3 and 16:9 examples (where 4:3 is now a variant class).

It looks like the use of the heights needs a little adjustments.
And the newly added keyboard shortcut feature needs to be built and documented.

The stories on the "Docs" page appear cut off, but that appears to be more popover related? That is possibly something that was already fixed in main as I don't see that issue there.

2024-12-19 21:26 UTC, jawinn commented on components/coachmark/stories/coachmark.stories.js
Also, could you also add a new control categorized under Content, for changing the image? I was looking for this when I wanted to test with a different sized (portrait/square) image.

2025-01-06 22:20 UTC, marissahuysentruyt requested changes
I did a first pass and mainly focused on the stories and template files. 

❓ Do you know why the coach indicator has a class name with `--undefined` in it? Is it a size? I'm unsure if it's coming from coach mark or popover (I think it's popover?) so maybe that's something I can address in the popover PR. It's like this on `main` as well, so this is just a curiosity.
❓ What would you think about renaming the `WithMedia` story to actual be `Without media`? Just based on Figma, it seems like the coach mark has a cover image by default. If that's true (and I would have to check, I don't actually know- that's just a guess based on the dev mode component), the default story and the with media story are the same right now. We'd also have to fix the sentence-casing of the story name and put that documentation elsewhere: 
<img width="1043" alt="Screenshot 2025-01-06 at 5 11 35 PM" src="https://github.com/user-attachments/assets/a4ae3874-f917-4d28-a5a3-d18669298ccc" />

❓ Maybe we need to expedite those new keyboard command components. There's a few older cards for them ([css-230](https://jira.corp.adobe.com/browse/CSS-230) and [css-231](https://jira.corp.adobe.com/browse/CSS-231)), so maybe we just need a coachmark follow up for when those are done? Would _not_ having those block this currently? Just thinking out loud on this one...

I'll do a second pass for tokens & CSS tomorrow!

2025-01-06 22:27 UTC, cdransf commented on components/coachmark/stories/coachmark.stories.js
> +			name: "Image fixed height",
Totally makes sense! Just updated that.

2025-01-06 22:35 UTC, jawinn requested changes

2025-01-06 22:35 UTC, jawinn commented on components/coachmark/stories/coachmark.stories.js
Now that `spectrum-two` has the `.test.js` files for Chromatic, it'd be a good idea to make sure everything that we want covered by VRTs is added there. Things that come to mind are the fixed height media, and the regular media with a landscape image that is affected by its minimum height.

2025-01-06 22:39 UTC, cdransf commented on components/coachmark/index.css
> +	margin-block-end: calc(var(--mod-coachmark-step-to-bottom, var(--spectrum-coachmark-step-to-bottom: )) - var(--mod-coachmark-padding, var(--spectrum-coachmark-padding)));
Oops! Fixed that.

2025-01-06 22:40 UTC, cdransf commented on components/coachmark/stories/coachmark.stories.js
> +			control: { type: "file", accept: ".svg,.png,.jpg,.jpeg,.webc" },
Added this in [2e2014](https://github.com/adobe/spectrum-css/pull/3412/commits/2e2014d31533e29c8dec6c5e03707f3dca66b70a) after @marissahuysentruyt's comment above. 🚀

2025-01-06 22:56 UTC, cdransf commented on components/coachmark/stories/coachmark.stories.js
>  		hasImage: false,
Would this then make the `With Media` example on the docs page unnecessary if the default has media?

<img width="1020" alt="image" src="https://github.com/user-attachments/assets/ccb3bc41-132a-478e-8f5c-7e21565dd070" />

2025-01-06 23:52 UTC, cdransf commented on components/coachmark/stories/coachmark.stories.js
>  		hasImage: false,
@marissahuysentruyt @jawinn I updated the stories in this commit [0008d0](https://github.com/adobe/spectrum-css/pull/3412/commits/0008d0a9b10a582c61b07e2c83c01baafea91ddb). If we run with...

```
hasActionMenu: false,
hasImage: true
```

...as default args, I've shuffled around the leading example to adhere to that state, the second in that block to show the action menu on and the media off. The 2nd block now shows the media variations added in the S2 migration.

2025-01-07 00:03 UTC, cdransf commented on components/coachmark/stories/coachmark.stories.js
> +	image: "example-card-landscape.png",
I updated the height(s) in [0008d0](https://github.com/adobe/spectrum-css/pull/3412/commits/0008d0a9b10a582c61b07e2c83c01baafea91ddb) while adjusting other aspects of the story(ies). ✨

2025-01-08 22:08 UTC, marissahuysentruyt commented on components/coachmark/stories/template.js
>  			${when(
This is unrelated to the work you've done, but the new line changes are messing with me! Is that a new VS code plugin I need or something? I'm so used to the `when()` block arguments being on the same line, I have to get used to it!

2025-01-08 22:11 UTC, cdransf commented on components/coachmark/stories/template.js
>  			${when(
That's zed doing that on save -- I suppose I can revert if we have a strict preference. 😅

2025-01-10 17:08 UTC, jawinn requested changes
I think the new approach for the keyboard shortcuts is working well, and the image examples look good now. Thanks for adding those additional tests.

I noticed a couple things:

1. Docs page examples are missing their title text for some reason 
2. Can you add docs and a story to the Docs page for Keyboard shortcuts?
3. The font family for the keyboard shortcuts should be defined; right now it's using the browser default. We have a monospace font: `--spectrum-code-font-family`.
4. Nit pick: I'd categorize the "Has keyboard shortcuts" control under "Component"
5. I noticed that there are some vertical spacing differences going on in the specs. I first noticed on the space between the shortcuts appearing much too large when the action button is present:
![Screenshot 2025-01-10 at 11 51 11 AM](https://github.com/user-attachments/assets/7c9d38d6-d3da-4cdb-9ee3-096801994304)
![Screenshot 2025-01-10 at 9 42 11 AM](https://github.com/user-attachments/assets/09ce4e06-cd05-4a9e-bf09-820499a8f693)

Digging into this a little more, it looks like there is also a small amount of extra space below the header when there is an action button, and no keyboard shortcuts. There's also some extra space above the text, making the edge to text more than the overall padding.

This seems to be related to fact that in the specs, the spacing and padding tokens defined are measuring to the text bounds and aren't taking into account the action button, so there is extra space created that is the difference between the action button height and the title text's line height. :/ 

Setting a magenta background on the text here helps illustrate:
![Screenshot 2025-01-10 at 11 02 37 AM](https://github.com/user-attachments/assets/bc252b38-024e-4d0b-9f53-61a27be740e5)
I experimented with this a little and I think that the simplest solution may be to use a negative margin on the action button (here I set `-6px` for both top and bottom):
![Screenshot 2025-01-10 at 11 02 08 AM](https://github.com/user-attachments/assets/06ce47b6-dec2-4815-b678-4cf99bf3f778)
That may need a custom var to also account for large platform scale. The value _could_ be figured out with a `calc()` with a `max()`, though it would be a little complex...

6. What sort of considerations should be made for wrapping and responsiveness?

I'm not sure what the design intentions would be in this situation:
![Screenshot 2025-01-10 at 11 18 11 AM](https://github.com/user-attachments/assets/0b9bc58a-87e9-4e9a-be72-57c59ae62281)
Looking at the large platform scale, the no wrap could cause some overflow issues:
![Screenshot 2025-01-10 at 11 16 55 AM](https://github.com/user-attachments/assets/4163d1bd-5031-403d-a7d7-99167b5e967f)

2025-01-23 19:31 UTC, marissahuysentruyt requested changes
This is looking pretty nice after the rebase! I had a very long thought, and wasn't quite sure where to put it, so I apologize- it's going here 😆 

-----
I hope I'm not backtracking on old comments, but I'm second-guessing our Default story on the docs page currently (technically `Standard`). 

I don't find it very clear _what_ the actual default coach mark is. According to Figma, their default component is something like hasImage: true, hasActionMenu: false, imageIsFixedHeight: false, hasPagination: true, (and you put all of those in the default args). I think it would be clearer to maybe put the no-action-menu-no-image in a separate story all by itself. Then `Standard` and this new "No media, no action menu" story are just bound to `Template()`. 

Just quickly, some more story ideas I had for the docs page:

`export const Standard = Template.bind({}); `(showcases just the default coachmark, and we'd add documentation that the default coach mark has an image and doesn't have an action menu). 
<img width="1041" alt="Screenshot 2025-01-23 at 1 23 56 PM" src="https://github.com/user-attachments/assets/8a01f05a-c3bb-45c5-b678-bdd3e64e91cb" />

```
export const StandardNoMedia = Template.bind({});
StandardNoMedia.storyName = "Default, no media";
StandardNoMedia.args = {
	hasImage: false,
};
```
<img width="1038" alt="Screenshot 2025-01-23 at 1 24 03 PM" src="https://github.com/user-attachments/assets/211642ec-15a0-4a7a-806a-4ac6d8038a7c" />

Based on the code comment, the `CoachmarkMenuStatesTemplate` should show the closed action menu and the open action menu. I would have probably kept that `CoachmarkMenuStatesTemplate` basically as it was (but fix up the headings for open/closed, and a missing isOpen: false), but then another story could be:
```
export const WithActionMenu = CoachmarkMenuStatesTemplate.bind({});
WithActionMenu.storyName = "With action menu";
WithActionMenu.args = {
	hasActionMenu: true,
};
```
<img width="1045" alt="Screenshot 2025-01-23 at 1 24 10 PM" src="https://github.com/user-attachments/assets/e109ab65-3230-4547-b69f-7c69cd51a0ae" />

I get what we're trying to do with these variants & stories, and just trying to show all the possible options. We could also add some additional documentation at the top of the page to clarify "all coach marks can have any combination of action menu, media, and keyboard shortcut options." [Steplist does this](https://opensource.adobe.com/spectrum-css/?path=/docs/components-steplist--docs) with a callout to "all steplists can be static or interactive." Then it covers everything in a centralized place.  

I definitely like Josh's comments about just adding more stories- I think it clarifies the options for users, and just separates all of the information a little better to make it easier to digest.

2025-01-23 19:31 UTC, marissahuysentruyt commented on components/coachmark/stories/coachmark.stories.js
> +	hasKeyboardShortcut: false,
Could we put this up with the default args instead? Like line 91ish? that matches how other components are, at least in my head.

2025-01-23 19:31 UTC, marissahuysentruyt commented on components/coachmark/stories/coachmark.stories.js
> +	},
I think there are 3 stories with additional parameters for the 450px story heights. I vote we just delete all of these repetitions, and update the default `docs.story.height: "300px"` to the 450. Then we only have to redefine that one 725px story. 🥳

2025-01-23 22:23 UTC, cdransf commented on components/coachmark/stories/coachmark.stories.js
> +/** Images and media have a minimum height and can grow with the parent component. Fixed height media is constrained to a 4:3 aspect ratio. */
Sure can! Added:

```
/** Images and media have a minimum height and can grow with the parent component. Fixed height media is constrained to a 4:3 aspect ratio by applying the spectrum-CoachMark-image-wrapper--fixedHeight class. */
```

2025-01-23 22:23 UTC, cdransf commented on components/coachmark/stories/coachmark.stories.js
>  	hasImage: true,
Committed this one! Thank you!

2025-01-23 22:23 UTC, cdransf commented on components/coachmark/stories/coachmark.stories.js
> +
Committed this one! Thank you!

2025-01-23 22:32 UTC, cdransf commented on .changeset/nice-cows-shout.md
> +Adds `--spectrum-coachmark-media-fixed-height` for fixed `4:3` image variant and an accompanying `--mod-coachmark-media-fixed-height` mod. This variation has been added to the `coachmark` component s
Updated that to `Fixed image height`. 👍🏻 

I'll get this updated to highlight the keyboard shortcut and add other properties to the table.

2025-01-23 22:33 UTC, cdransf commented on components/coachmark/stories/template.js
> +export const CoachMarkMediaStateTemplates = (args, context) =>
All set! ✨

2025-01-23 22:37 UTC, cdransf commented on components/coachmark/stories/template.js
> +				heading: "With shortcut menu, without action menu",
Right on! Updated those.

2025-01-23 22:42 UTC, cdransf commented on components/coachmark/stories/template.js
> +				heading: "With fixed height",
Yeah, I like that! Just updated it. ✨

2025-01-23 22:42 UTC, cdransf commented on components/coachmark/stories/template.js
> +				content: Template({ ...args, hasKeyboardShortcut: true, hasActionMenu: true }, context),
Fixed this one too! 👍🏻

2025-01-24 20:25 UTC, cdransf commented on .changeset/nice-cows-shout.md
> +| --spectrum-coach-mark-pagination-body-size | --spectrum-coach-mark-pagination-body-font-size |
Updated it with a component-specific subset from metadata — let me know what you think. 😄

2025-01-24 20:28 UTC, cdransf commented on .changeset/nice-cows-shout.md
> +Adds `--spectrum-coachmark-media-fixed-height` for fixed `4:3` image variant and an accompanying `--mod-coachmark-media-fixed-height` mod. This variation has been added to the `coachmark` component s
Added a blurb on the keyboard shortcut. ✅

2025-02-24 16:24 UTC, jawinn requested changes
We're pretty close on this one! A few suggestions and that one spacing issue still needs a solution.

2025-02-24 16:24 UTC, jawinn commented on components/coachmark/stories/coachmark.stories.js
> +/** Images and media have a minimum height and can grow with the parent component. Fixed height media is constrained to a 4:3 aspect ratio by applying the spectrum-CoachMark-image-wrapper--fixedHeigh
```suggestion
/** Images and media have a minimum height and can grow with the parent component. Fixed height media is constrained to a 4:3 aspect ratio by applying the `spectrum-CoachMark-image-wrapper--fixedHeight` class. When this fixed height class is used, the height can be customized using the modifiable custom property `--mod-coachmark-media-fixed-height`.  */
```

2025-02-24 16:24 UTC, jawinn commented on components/coachmark/index.css
I'm still seeing the issue with extra space above and below the title when the action button is present, [described in issue 5 in this comment](https://github.com/adobe/spectrum-css/pull/3412#pullrequestreview-2542996354).

![Screenshot 2025-01-10 at 11 02 37 AM](https://github.com/user-attachments/assets/bc252b38-024e-4d0b-9f53-61a27be740e5)

We had chatted about that a while back with the design team in Slack, but it looks like we need to follow-up with them to see if they can provide a token we can use (there were a few options where "The design team provides another token that we can use. Could `--spectrum-spacing-50` be what we need?" seemed like the best one).

2025-02-24 16:30 UTC, cdransf commented on components/badge/stories/template.js
They were! Thanks for catching — I didn't know about `literal` either. That's awesome! 👏

2025-03-11 23:14 UTC, cdransf commented on components/coachmark/index.css
I'm digging into this more now and — I may be wrong here — but there's also a shift between the action button and the image when it's rendered. I'm going to try and step through the spacing to see what I _can_ adjust to try and eliminate that shift and then see if I can arrive at a cleaned up solution. 😅

(I tried applying `--spectrum-spacing-50` and it seemed too small to me?)

2025-03-21 16:33 UTC, castastrophe commented on .changeset/nice-cows-shout.md
> +# S2 coachmark migration
When this gets injected into the changelog, it'll be an h4 level so maybe we update these to start at h4?

2025-03-21 16:33 UTC, castastrophe commented on .changeset/nice-cows-shout.md
> +| Before                                     | After                                           |
😍 love these tables!

2025-03-21 16:33 UTC, castastrophe commented on .changeset/nice-cows-shout.md
> +Adds `--spectrum-coachmark-media-fixed-height` for fixed `4:3` image variant and an accompanying `--mod-coachmark-media-fixed-height` mod. This variation has been added to the `coachmark` component s
Great summary, thanks for outlining this!

2025-03-21 16:33 UTC, castastrophe commented on components/badge/stories/template.js
> +			${when(label, () => html`${unsafeHTML(`<${tag} class="${rootClass}-label">${label}</${tag}>`)}`)}
Nice technique

2025-03-21 16:33 UTC, castastrophe commented on components/coachmark/stories/template.js
> +						: ""}"
This looks like a good opportunity to use classMap; might be a little easier to read than the ternary format.

2025-03-21 16:46 UTC, cdransf commented on components/coachmark/stories/template.js
> +						: ""}"
Good catch! I updated that and also cleaned up a couple of stories that shouldn't have been showing in the sidebar. ✨

2025-03-21 19:03 UTC, jawinn requested changes

2025-03-21 19:03 UTC, jawinn commented on components/coachmark/index.css
So we'll need to make sure both platform scales are supported, and wrapping title text is supported. It's pretty tricky with how tokens are currently defined.

I experimented a bit, and rather than using the multipliers in [b665a97](https://github.com/adobe/spectrum-css/pull/3412/commits/b665a975f8259a134db44a5dc106dc8162659608), the simplest way that I can find is still to use a negative margin on the button. Something like these values seemed pretty close:

```
.spectrum-CoachMark-action-menu {
	/* Negative margins to correct spacing which uses token specs that measure to just the title text. */
	margin-block: var(--mod-coachmark-action-menu-vertical-offset, var(--spectrum-coachmark-action-menu-vertical-offset));
}

custom/medium-vars.css
--spectrum-coachmark-action-menu-vertical-offset: -4px;

custom/large-vars.css
--spectrum-coachmark-action-menu-vertical-offset: -6px;
```

It looks like the wrapping alignment of the title text with the button needs to change (`align-items: flex-start;` on the header?). I saw this in the Figma dev playground for the component:
<img width="263" alt="Screenshot 2025-03-21 at 11 39 24 AM" src="https://github.com/user-attachments/assets/d81c59a8-eba3-465c-9452-85e6a1f48d69" />
Can you also make sure that multiple lines of wrapping title text is included in the tests file as part of that, so it's covered in VRTs?

2025-03-26 14:31 UTC, marissahuysentruyt commented on components/coachmark/stories/coachmark.stories.js
> +	imageIsFixedHeight: false,
We can actually delete the `hasImage` `hasActionMenu`, and `imageIsFixedHeight` args for `Standard` (since they're just set to the same values anyways).

2025-03-26 14:46 UTC, marissahuysentruyt commented on components/coachmark/stories/template.js
> +						imageSource: "example-card-portrait.png",
@cdransf Just wanted to ping you on this again. I believe we can remove some of the repetitive args. `hasImage` can be deleted as well as `imageSource`!

2025-03-26 14:57 UTC, marissahuysentruyt commented on components/coachmark/stories/coachmark.test.js
> +				"background-color": "var(--spectrum-gray-50, white)",
I think this `wrapperStyles` is probably correct, but I just wanted to double check if we actually wanted this to be the `customStyles`. 

`wrapperStyles` is effecting the whole test container (which again, I think is probably intentional).

https://github.com/user-attachments/assets/a1001f39-db83-4b8a-8d27-502ee9a80ba9

`customStyles` would set the background for the coach mark itself, but...I don't think that's really adding any value. I was thinking we wanted to capture the rounded corners, but I think it's actually popover that sets the rounded corners.

<img width="400" alt="Screenshot 2025-03-26 at 10 55 51 AM" src="https://github.com/user-attachments/assets/335935e6-9224-4801-bbb0-8902d3c43ea2" />

2025-03-26 16:39 UTC, cdransf commented on components/badge/stories/template.js
> +		tag = "div",
Absolutely — I reverted the badge template back to what we have on `spectrum-two`.

2025-03-26 16:39 UTC, cdransf commented on components/coachmark/stories/coachmark.stories.js
> +	imageIsFixedHeight: false,
Done! 🚀

2025-03-26 16:40 UTC, cdransf commented on components/coachmark/stories/coachmark.stories.js
> +MediaStates.storyName = "Media states";
I think that's great — it reflects that they are options rather than states based on the selected options. ✨

2025-03-26 17:35 UTC, cdransf commented on components/coachmark/stories/coachmark.test.js
> +				"background-color": "var(--spectrum-gray-50, white)",
That's a good callout — I don't think those styles add much and they are repetitive. I dropped them and the tests actually look better without them. 😅

2025-03-26 21:07 UTC, marissahuysentruyt reviewed
Overall, the tokens are looking really great! A few tiny things I noticed that I wanted to bring with you.

2025-03-26 21:07 UTC, marissahuysentruyt commented on components/coachmark/index.css
> +	inline-size: var(--mod-coachmark-width, var(--spectrum-coachmark-width));
I think our current preference is to keep the custom property definitions separate from our style definitions. So we would end up with a separate, second `.spectrum-CoachMark` selector, with these 4 styles in it. 

Feel free to get a second opinion on that- maybe I'm mistaken!

2025-03-26 21:13 UTC, marissahuysentruyt commented on components/coachmark/index.css
> +	margin-block: var(--mod-coachmark-action-menu-vertical-offset, var(--spectrum-coachmark-action-menu-vertical-offset));
ope- scratch my question on the vertical offset. I'll read Josh's comment about it 😬

2025-03-27 12:53 UTC, marissahuysentruyt approved these changes
I think this is looking really great! Thanks so much for sticking with it, fielding all of the keyboard shortcut questions! Great work 🎉

2025-03-31 13:58 UTC, jawinn requested changes

2025-03-31 13:58 UTC, jawinn commented on components/coachmark/index.css
Thanks for updating the margin there and adding those custom vars.

Looking at the testing link, it looks like the flex alignment for the header and action button still needs adjustment:
<img width="325" alt="Screenshot 2025-03-31 at 9 53 47 AM" src="https://github.com/user-attachments/assets/5dad656b-ffb5-4eb5-ad0f-7f37d1865263" />

2025-04-01 18:47 UTC, jawinn approved these changes

2025-04-01 21:49 UTC, merged