Aramos-adobe/css1035-infield-progress-cirlce-s2-migration
adobe/spectrum-css pull request #3430
Opened 2024-12-05 19:12 UTC by aramos-adobe

## Description

The infield progresscirlce is a subcomponent of the progress circle which is used in button, combobox, and picker. It's smaller in block size and has its own tshirt sizing.

## Mods

`--mod-progress-cirlce-stroke-width`

## How and where has this been tested?

Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the author.

### Validation steps

  1. Open the storybook for the infield progress circle:
    - [x] Toggle Intedeterminate mode
    - [x] Exists in combobox, button, picker components isLoading states

### Regression testing

Validate:

1. The documentation pages for at least two other components are still loading, including:

- [ ] The pages render correctly, are accessible, and are responsive.

2. If components have been modified, VRTs have been run on this branch:

- [ ] VRTs have been run and looked at.
- [ ] Any VRT changes have been accepted (by reviewer and/or PR author), or there are no changes.

## Screenshots

## To-do list

- [ ] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [ ] I have updated relevant storybook stories and templates.
- [ ] I have tested these changes in Windows High Contrast mode.
- [ ] If my change impacts **other components**, I have tested to make sure they don't break.
- [ ] If my change impacts **documentation**, I have updated the documentation accordingly.
- [ ] ✨ This pull request is ready to merge. ✨

2025-01-16 20:57 UTC, marissahuysentruyt commented on components/infieldprogresscircle/metadata/infieldprogresscircle.yml
This is a hold-over from the old docs site. This file can be deleted entirely.

2025-01-16 22:14 UTC, marissahuysentruyt requested changes
I know I left a barrage of comments! This is moving along nicely, most of comments are just clean up after the rebase. 

Now that `spectrum-two` is up to date, we have all of our test files, so we'll need a brand new `infieldprogresscircle.test.js` file and tests written 🥳 We should also update the documentation page with the new stories and docs.

2025-01-16 22:14 UTC, marissahuysentruyt commented on components/infieldprogresscircle/stories/template.js
> +	rootClass,
I also wonder if `spectrum-InfieldProgressCircle` should actually be here, instead of within the custom classes of progress circle.

2025-01-21 17:40 UTC, aramos-adobe commented on .changeset/flat-snails-admire.md
> +The infield progresscirlce is a subcomponent of the progress circle which is used in button, combobox, and picker. It's smaller in block size and has its own tshirt sizing.
@marissahuysentruyt Looks like a new thing. Updating it now

2025-01-28 23:00 UTC, marissahuysentruyt requested changes
This is getting close- thanks for splitting this off from the other progress circle migration!

My main set of concerns I think is just related to this _not_ being an already-published NPM package. So the `ComponentDetails` cards don't render at the top of this page since we can't fetch the data from NPM. There's also no metadata.json in the `dist` output for this component. I'm not sure where to start with that unfortunately (it might be a @castastrophe question)

If I could be really picky, I'd like to request a change to the regular progress circle controls. I noticed that the `value` control in `progresscircle.stories.js` doesn't have maybe all of the usual settings, like name, description, etc. Could we update that so it matches the other controls better? This is the same control in progress bar: 
```
value: {
	name: "Percent filled",
	type: { name: "number" },
	table: {
		type: { summary: "number" },
		category: "Content",
	},
	control: { type: "range", min: 0, max: 100,},
	if: { arg: "isIndeterminate", truthy: false },
},
```
It's a little more descriptive for users, categorizes`value` into the "Content" set of controls, and adds that conditional, so it won't even show for a default story if you wanted to get real fancy.

<img width="755" alt="Screenshot 2025-01-28 at 5 51 01 PM" src="https://github.com/user-attachments/assets/ef9259f2-0417-4a93-9716-bb7b41be9645" />

2025-01-28 23:00 UTC, marissahuysentruyt commented on components/infieldprogresscircle/stories/infieldprogresscircle.stories.js
> +import packageJson from "../package.json";
Oh! We need the metadata.json stuff.

```suggestion
import metadata from "../dist/metadata.json";
import packageJson from "../package.json";
```

2025-01-28 23:00 UTC, marissahuysentruyt commented on components/infieldprogresscircle/package.json
> +  "version": "0.0.0",
Maybe get a second opinion, but should this version number be 1.0.0? Or does that happen when changesets creates a release for us to merge?

2025-01-28 23:00 UTC, marissahuysentruyt commented on components/infieldprogresscircle/package.json
> +  ],
Would you double check the package.json for a few things? I used the regular progress circle package.json as a comparison, and I think we're missing a few things. 

- This `files` key looks like it's been updated with `"stories/*` and `"metadata/*`
- We're missing the `exports` block.
- We're missing the `devDependencies` block.
- We might have to double check the tokens packages declared for those peerDependencies and devDependencies.
- For the description up at the top of this file, we can separate out the component name. "The Spectrum CSS infield progress circle component" so that "infieldprogresscircle" isn't just one word.
- I also get a warning in my editor that "'peerDependencies' should be before 'keywords'" (not sure if you were getting that from eslint)

2025-01-28 23:00 UTC, marissahuysentruyt commented on components/infieldprogresscircle/index.css
> +	padding-block: var(--spectrum-in-field-progress-circle-edge-to-fill);
I believe the preference is not to use the tokens directly in style property definitions like this. Instead of `padding-block: var(--spectrum-in-field-progress-circle-edge-to-fill);`, could you make another custom property for this, above the mods, and then use the custom prop to define `padding-block`? 

```
.spectrum-InfieldProgressCircle {
	--spectrum-infieldprogresscircle-padding-block: var(--spectrum-in-field-progress-circle-edge-to-fill);
// mods are here
}
... // t-shirt size stuff you already have

.spectrum-InfieldProgressCircle {
	padding-block: var(--spectrum-infieldprogresscircle-padding-block);
...
}
```

2025-01-28 23:00 UTC, marissahuysentruyt commented on components/infieldprogresscircle/index.css
> +	--mod-progress-circle-thickness: var(--mod-progress-cirlce-stroke-width, 2px);
This 2px- I see in Figma that there's a token `progress-circle-thickness-small`. Should we be using that instead of the hardcoded 2px? 

Also, do we want to introduce a mod for this? Are we creating a mod for a mod? 🙃 I don't know the answer to that question, but is this infield progress circle supposed to just overwrite any of the progress circle mods, including `--mod-progress-circle-stroke-width`? Should this line just be `--mod-progress-circle-thickness: var(--spectrum-progress-circle-thickness-small)`?

And if not- I caught another misspelling of circle in that `--mod-progress-circle-stroke-width`. Those pesky L's and C's 😆

2025-01-28 23:00 UTC, marissahuysentruyt commented on components/infieldprogresscircle/stories/infieldprogresscircle.stories.js
> +	Template: Template,
We can just write `Template,` here, as opposed to `Template: Template` if you want to reduce some repetitiveness.

Same thing for the Indeterminate story.

2025-01-28 23:00 UTC, marissahuysentruyt commented on components/infieldprogresscircle/stories/infieldprogresscircle.stories.js
> +	isIndeterminate: false,
Any time we have `isIndeterminate: false`, we can just rely on progress circle's default arg, where `isIndeterminate` is already false. We don't need to redeclare it!

2025-01-28 23:00 UTC, marissahuysentruyt commented on components/textfield/stories/template.js
>  			customClasses: customProgressCircleClasses,
Should this be `customInfieldProgressCircleClasses`? Is that the intention here?

2025-01-28 23:00 UTC, marissahuysentruyt commented on components/infieldprogresscircle/stories/template.js
> +	...item
What's the `...item` for here? Is that referencing the parent component that infield PC would be in, like the picker or button?

2025-01-29 15:20 UTC, marissahuysentruyt commented on components/infieldprogresscircle/project.json
> +		"lint": {},
```suggestion
"lint": {},
"report": {},
```

Looking at some other project.jsons, I think we need a `"report": {}` line.

2025-01-29 15:28 UTC, marissahuysentruyt commented on components/infieldprogresscircle/stories/infieldprogresscircle.stories.js
> +import packageJson from "../package.json";
Something might be missing somewhere. It doesn't look like infield progress circle is correctly building the metadata.json in its `dist` file.

2025-01-31 19:32 UTC, aramos-adobe commented on components/infieldprogresscircle/stories/template.js
> +	...item
It's just to spread the rest of props nested in Progress Circle.

2025-02-04 20:24 UTC, marissahuysentruyt commented on components/infieldprogresscircle/stories/template.js
> +	...item
aahhh right. Thanks!

2025-02-04 20:49 UTC, marissahuysentruyt requested changes
Excellent work on this! I found a small wording suggestion and then one typo, but overall this is looking really great!

I think there's only one more place we have to update from "progress circle" to infield progress circle. https://github.com/adobe/spectrum-css/blob/67d61615ab3f50637207ca7c4e9e21c0f1bb1296/components/combobox/stories/template.js#L66

I only noticed it because the changeset mentioned combobox, but I thought we didn't make any changes to combobox! I think in the combobox template.js file, we should change the `customProgressCircleClasses` to the `customInfieldProgressCircle` classes so it gets passed properly to textfield.

2025-02-04 20:49 UTC, marissahuysentruyt commented on .changeset/flat-snails-admire.md
> +`--mod-progress-cirlce-stroke-width`
Just a typo with "circle"

```suggestion
`--mod-progress-circle-stroke-width`
```

2025-02-04 20:49 UTC, marissahuysentruyt commented on .changeset/flat-snails-admire.md
> +In-field progress circle is a new component created to replace progress circle (size S) in t-shirt size components such as: buttons, combo boxes, pickers. Comes in four sizes: (S, M, L, XL), has upda
Maybe we can make it clearer that we updated button, picker, and textfield to use infield progress circle? 

```suggestion
In-field progress circle is a new component created to replace progress circle (size S) in t-shirt size components. The button, textfield, combo box, and picker `template.js` files have all been updated to call for infield progress circles. This component comes in four sizes: (S, M, L, XL), has updated color variants (default, white, black), and has a unified track thickness.
```

2025-02-04 23:30 UTC, aramos-adobe commented on .changeset/flat-snails-admire.md
> +`--mod-progress-cirlce-stroke-width`
Man I cannot spell circle at all 😅

2025-02-05 19:08 UTC, marissahuysentruyt reviewed
Nice work on this! It really is looking fabulous 🤩 I have just a few small clean up things I think we could do before I'm good to approve!

1. I think we should remove the mods section of the changeset completely. They're not infield progress circle mods (we're using the regular progress circle mods as passthroughs for this component instead), so I'm not sure they need any specific attention drawn to them in the changeset. Feel free to get a second opinion on that though if you feel differently. 

2. I would drop the https://github.com/adobe/spectrum-css/pull/3430/commits/56c68064e6d702978b45b805ce8342eb8a5863d7 commit that's listed in the commit history. That work looks like it's already in the `spectrum-two` branch but under a different SHA, so I wouldn't want to introduce duplicate work or commits or anything. (`git rebase -i spectrum-two` should do it)

<img width="1098" alt="Screenshot 2025-02-05 at 1 59 01 PM" src="https://github.com/user-attachments/assets/6b483158-0b2f-4429-a050-e0d2f88cf9a0" />

I think when this branch was merged (as opposed to being rebased) with `spectrum-two`, it got the older commit SHA. But then when `spectrum-two` was rebased and pushed up, that's when things got a little off. I almost always (possibly 100% of the time) do rebasing now instead of merging

2025-02-05 20:06 UTC, marissahuysentruyt approved these changes
Thank you so much for all of your hard work on this! It looks AMAZING! 
![amazing](https://github.com/user-attachments/assets/526799e5-eb99-4dff-81b2-c95baca8fc65)

2025-02-06 17:32 UTC, rise-erpelding requested changes
The component looks great! I have only a few changes to request here but they're mostly in the `package.json`, it looks like components' `package.json`s might have changed in the recent rebase so we'd just want to align more closely with those changes.

2025-02-06 20:23 UTC, rise-erpelding approved these changes
![](https://media.giphy.com/media/TKQgPvfYxaoOIXn16h/giphy.gif?cid=ecf05e47y052dmkvm5icbkmctuhnrq720xagb5113gxsw69y&ep=v1_gifs_search&rid=giphy.gif&ct=g)

2025-02-06 20:27 UTC, merged