fix: ramp slider (#829)
adobe/spectrum-css pull request #923
Opened 2020-09-17 19:39 UTC by bernhard-adobe

Adding back ramp-slider and removing color-slider.

## Description
Addresses issue #829 

- added back ramp-slider
- removed color-slider from slider page that is now it's own component under [/docs/colorslider.html](/docs/colorslider.html)

## How and where has this been tested?
URL: http://localhost:3000/docs/slider.html
Chrome Version 85.0.4183.102 (Official Build) (64-bit) on MacOS

## Screenshots

<img width="635" alt="Screen Shot 2020-09-17 at 15 07 53" src="https://user-images.githubusercontent.com/52184321/93517961-284f0080-f8fa-11ea-92bd-85bba0e0021b.png">

## To-do list

- [x] If my change impacts other components, I have tested to make sure they don't break.
- [x] If my change impacts documentation, I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).

- [x] This pull request is ready to merge.

2020-09-17 19:52 UTC, lazd requested changes
Commit message needs to include:

```
BREAKING CHANGE: Slider color variant removed, used Color Slider component
```

Also need migration guide.

2020-09-21 20:06 UTC, bernhard-adobe commented
Good points @lazd .
I added a migration guide. Unfortunately your suggested commit message is not working because of the commit rules with uppercases:
```
$ g commit -m "BREAKING CHANGE: Slider color variant removed, used Color Slider component"
husky > commit-msg (node v12.16.2)
⧗   input: BREAKING CHANGE: Slider color variant removed, used Color Slider component
✖   header must not be longer than 72 characters, current length is 74 [header-max-length]
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 3 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

```

I used instead `g commit -m "fix: breaking change: slider color variant moved to color slider. (#850)"`
I also added the breaking-change label.

2020-09-21 22:27 UTC, GarthDB commented
The disabled color seems to have changed for ramp slider. Is that a result of the tokens changing?

2020-09-22 16:01 UTC, lazd commented on components/slider/metadata/slider.yml
> +      ### Color Slider moved  out of Sliders into it's own component
```suggestion
      ### Color slider is now a separate component
```

2020-09-22 16:02 UTC, lazd commented on components/slider/metadata/slider.yml
> +      Replace class names starting with `.spectrum-Slider` to `.spectrum-ColorSlider`.
```suggestion
      Replace class names starting with `.spectrum-Slider` with `.spectrum-ColorSlider`.
```

2020-09-22 17:35 UTC, lazd approved these changes

2020-09-22 20:58 UTC, merged